// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accesstoken.proto

package net.hzbox.vj.company.proto;

public final class AccessTokenProtos {
  private AccessTokenProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AccessTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AccessToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional uint32 company_id = 2;</code>
     */
    int getCompanyId();

    /**
     * <code>optional string access_token = 3;</code>
     */
    String getAccessToken();
    /**
     * <code>optional string access_token = 3;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>optional string js_api_ticket = 4;</code>
     */
    String getJsApiTicket();
    /**
     * <code>optional string js_api_ticket = 4;</code>
     */
    com.google.protobuf.ByteString
        getJsApiTicketBytes();

    /**
     * <code>optional uint32 type = 5;</code>
     */
    int getType();

    /**
     * <code>optional uint32 agent_id = 6;</code>
     */
    int getAgentId();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AccessToken}
   */
  public  static final class AccessToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AccessToken)
      AccessTokenOrBuilder {
    // Use AccessToken.newBuilder() to construct.
    private AccessToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AccessToken() {
      id_ = 0;
      companyId_ = 0;
      accessToken_ = "";
      jsApiTicket_ = "";
      type_ = 0;
      agentId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AccessToken(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 16: {

              companyId_ = input.readUInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              jsApiTicket_ = s;
              break;
            }
            case 40: {

              type_ = input.readUInt32();
              break;
            }
            case 48: {

              agentId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_AccessToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.class, net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 2;
    private int companyId_;
    /**
     * <code>optional uint32 company_id = 2;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 3;
    private volatile Object accessToken_;
    /**
     * <code>optional string access_token = 3;</code>
     */
    public String getAccessToken() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>optional string access_token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JS_API_TICKET_FIELD_NUMBER = 4;
    private volatile Object jsApiTicket_;
    /**
     * <code>optional string js_api_ticket = 4;</code>
     */
    public String getJsApiTicket() {
      Object ref = jsApiTicket_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jsApiTicket_ = s;
        return s;
      }
    }
    /**
     * <code>optional string js_api_ticket = 4;</code>
     */
    public com.google.protobuf.ByteString
        getJsApiTicketBytes() {
      Object ref = jsApiTicket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jsApiTicket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>optional uint32 type = 5;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int AGENT_ID_FIELD_NUMBER = 6;
    private int agentId_;
    /**
     * <code>optional uint32 agent_id = 6;</code>
     */
    public int getAgentId() {
      return agentId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (companyId_ != 0) {
        output.writeUInt32(2, companyId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accessToken_);
      }
      if (!getJsApiTicketBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, jsApiTicket_);
      }
      if (type_ != 0) {
        output.writeUInt32(5, type_);
      }
      if (agentId_ != 0) {
        output.writeUInt32(6, agentId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, companyId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accessToken_);
      }
      if (!getJsApiTicketBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, jsApiTicket_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, type_);
      }
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, agentId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken other = (net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && getAccessToken()
          .equals(other.getAccessToken());
      result = result && getJsApiTicket()
          .equals(other.getJsApiTicket());
      result = result && (getType()
          == other.getType());
      result = result && (getAgentId()
          == other.getAgentId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + JS_API_TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getJsApiTicket().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AccessToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AccessToken)
        net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_AccessToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.class, net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        companyId_ = 0;

        accessToken_ = "";

        jsApiTicket_ = "";

        type_ = 0;

        agentId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor;
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken build() {
        net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken buildPartial() {
        net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken result = new net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken(this);
        result.id_ = id_;
        result.companyId_ = companyId_;
        result.accessToken_ = accessToken_;
        result.jsApiTicket_ = jsApiTicket_;
        result.type_ = type_;
        result.agentId_ = agentId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken) {
          return mergeFrom((net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken other) {
        if (other == net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (!other.getJsApiTicket().isEmpty()) {
          jsApiTicket_ = other.jsApiTicket_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>optional uint32 company_id = 2;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional uint32 company_id = 2;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 company_id = 2;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private Object accessToken_ = "";
      /**
       * <code>optional string access_token = 3;</code>
       */
      public String getAccessToken() {
        Object ref = accessToken_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string access_token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string access_token = 3;</code>
       */
      public Builder setAccessToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_token = 3;</code>
       */
      public Builder clearAccessToken() {

        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_token = 3;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        accessToken_ = value;
        onChanged();
        return this;
      }

      private Object jsApiTicket_ = "";
      /**
       * <code>optional string js_api_ticket = 4;</code>
       */
      public String getJsApiTicket() {
        Object ref = jsApiTicket_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jsApiTicket_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string js_api_ticket = 4;</code>
       */
      public com.google.protobuf.ByteString
          getJsApiTicketBytes() {
        Object ref = jsApiTicket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsApiTicket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string js_api_ticket = 4;</code>
       */
      public Builder setJsApiTicket(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        jsApiTicket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string js_api_ticket = 4;</code>
       */
      public Builder clearJsApiTicket() {

        jsApiTicket_ = getDefaultInstance().getJsApiTicket();
        onChanged();
        return this;
      }
      /**
       * <code>optional string js_api_ticket = 4;</code>
       */
      public Builder setJsApiTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        jsApiTicket_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>optional uint32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional uint32 type = 5;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 type = 5;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private int agentId_ ;
      /**
       * <code>optional uint32 agent_id = 6;</code>
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>optional uint32 agent_id = 6;</code>
       */
      public Builder setAgentId(int value) {

        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 agent_id = 6;</code>
       */
      public Builder clearAgentId() {

        agentId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AccessToken)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AccessToken)
    private static final net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken();
    }

    public static net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AccessToken>
        PARSER = new com.google.protobuf.AbstractParser<AccessToken>() {
      public AccessToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AccessToken(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AccessToken> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AccessToken> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>optional string msg = 2;</code>
     */
    String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    boolean hasAccessToken();
    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getAccessToken();
    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder getAccessTokenOrBuilder();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      success_ = false;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder subBuilder = null;
              if (accessToken_ != null) {
                subBuilder = accessToken_.toBuilder();
              }
              accessToken_ = input.readMessage(net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accessToken_);
                accessToken_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AccessTokenProtos.Result.class, net.hzbox.vj.company.proto.AccessTokenProtos.Result.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 3;
    private net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken accessToken_;
    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    public boolean hasAccessToken() {
      return accessToken_ != null;
    }
    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getAccessToken() {
      return accessToken_ == null ? net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.getDefaultInstance() : accessToken_;
    }
    /**
     * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
     */
    public net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder getAccessTokenOrBuilder() {
      return getAccessToken();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (accessToken_ != null) {
        output.writeMessage(3, getAccessToken());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (accessToken_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAccessToken());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AccessTokenProtos.Result)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AccessTokenProtos.Result other = (net.hzbox.vj.company.proto.AccessTokenProtos.Result) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (hasAccessToken() == other.hasAccessToken());
      if (hasAccessToken()) {
        result = result && getAccessToken()
            .equals(other.getAccessToken());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasAccessToken()) {
        hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AccessTokenProtos.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.Result)
        net.hzbox.vj.company.proto.AccessTokenProtos.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AccessTokenProtos.Result.class, net.hzbox.vj.company.proto.AccessTokenProtos.Result.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AccessTokenProtos.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        msg_ = "";

        if (accessTokenBuilder_ == null) {
          accessToken_ = null;
        } else {
          accessToken_ = null;
          accessTokenBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.internal_static_net_hzbox_vj_company_proto_Result_descriptor;
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.Result getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AccessTokenProtos.Result.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.Result build() {
        net.hzbox.vj.company.proto.AccessTokenProtos.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AccessTokenProtos.Result buildPartial() {
        net.hzbox.vj.company.proto.AccessTokenProtos.Result result = new net.hzbox.vj.company.proto.AccessTokenProtos.Result(this);
        result.success_ = success_;
        result.msg_ = msg_;
        if (accessTokenBuilder_ == null) {
          result.accessToken_ = accessToken_;
        } else {
          result.accessToken_ = accessTokenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AccessTokenProtos.Result) {
          return mergeFrom((net.hzbox.vj.company.proto.AccessTokenProtos.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AccessTokenProtos.Result other) {
        if (other == net.hzbox.vj.company.proto.AccessTokenProtos.Result.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasAccessToken()) {
          mergeAccessToken(other.getAccessToken());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AccessTokenProtos.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AccessTokenProtos.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 1;</code>
       */
      public Builder clearSuccess() {

        success_ = false;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {

        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msg_ = value;
        onChanged();
        return this;
      }

      private net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken accessToken_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken, net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder, net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder> accessTokenBuilder_;
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public boolean hasAccessToken() {
        return accessTokenBuilder_ != null || accessToken_ != null;
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken getAccessToken() {
        if (accessTokenBuilder_ == null) {
          return accessToken_ == null ? net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.getDefaultInstance() : accessToken_;
        } else {
          return accessTokenBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public Builder setAccessToken(net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken value) {
        if (accessTokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accessToken_ = value;
          onChanged();
        } else {
          accessTokenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public Builder setAccessToken(
          net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder builderForValue) {
        if (accessTokenBuilder_ == null) {
          accessToken_ = builderForValue.build();
          onChanged();
        } else {
          accessTokenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public Builder mergeAccessToken(net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken value) {
        if (accessTokenBuilder_ == null) {
          if (accessToken_ != null) {
            accessToken_ =
              net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.newBuilder(accessToken_).mergeFrom(value).buildPartial();
          } else {
            accessToken_ = value;
          }
          onChanged();
        } else {
          accessTokenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public Builder clearAccessToken() {
        if (accessTokenBuilder_ == null) {
          accessToken_ = null;
          onChanged();
        } else {
          accessToken_ = null;
          accessTokenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder getAccessTokenBuilder() {

        onChanged();
        return getAccessTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      public net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder getAccessTokenOrBuilder() {
        if (accessTokenBuilder_ != null) {
          return accessTokenBuilder_.getMessageOrBuilder();
        } else {
          return accessToken_ == null ?
              net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.getDefaultInstance() : accessToken_;
        }
      }
      /**
       * <code>optional .net.hzbox.vj.company.proto.AccessToken access_token = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken, net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder, net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder>
          getAccessTokenFieldBuilder() {
        if (accessTokenBuilder_ == null) {
          accessTokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken, net.hzbox.vj.company.proto.AccessTokenProtos.AccessToken.Builder, net.hzbox.vj.company.proto.AccessTokenProtos.AccessTokenOrBuilder>(
                  getAccessToken(),
                  getParentForChildren(),
                  isClean());
          accessToken_ = null;
        }
        return accessTokenBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.Result)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.Result)
    private static final net.hzbox.vj.company.proto.AccessTokenProtos.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AccessTokenProtos.Result();
    }

    public static net.hzbox.vj.company.proto.AccessTokenProtos.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AccessTokenProtos.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AccessToken_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_Result_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021accesstoken.proto\022\032net.hzbox.vj.compan" +
      "y.proto\"z\n\013AccessToken\022\n\n\002id\030\001 \001(\r\022\022\n\nco" +
      "mpany_id\030\002 \001(\r\022\024\n\014access_token\030\003 \001(\t\022\025\n\r" +
      "js_api_ticket\030\004 \001(\t\022\014\n\004type\030\005 \001(\r\022\020\n\010age" +
      "nt_id\030\006 \001(\r\"e\n\006Result\022\017\n\007success\030\001 \001(\010\022\013" +
      "\n\003msg\030\002 \001(\t\022=\n\014access_token\030\003 \001(\0132\'.net." +
      "hzbox.vj.company.proto.AccessTokenB/\n\032ne" +
      "t.hzbox.vj.company.protoB\021AccessTokenPro" +
      "tosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_company_proto_AccessToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AccessToken_descriptor,
        new String[] { "Id", "CompanyId", "AccessToken", "JsApiTicket", "Type", "AgentId", });
    internal_static_net_hzbox_vj_company_proto_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_hzbox_vj_company_proto_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_Result_descriptor,
        new String[] { "Success", "Msg", "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
