// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_visible.proto

package net.hzbox.vj.company.proto;

public final class AppVisibleProtos {
  private AppVisibleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppVisibleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisible)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> 
        getAppVisibleDepartmentsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    int getAppVisibleDepartmentsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder> 
        getAppVisibleDepartmentsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
            int index);

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson>
        getAppVisiblePersonsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    int getAppVisiblePersonsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    java.util.List<? extends net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder>
        getAppVisiblePersonsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
            int index);

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag>
        getAppVisibleTagsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    int getAppVisibleTagsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder>
        getAppVisibleTagsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisible}
   */
  public  static final class AppVisible extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisible)
      AppVisibleOrBuilder {
    // Use AppVisible.newBuilder() to construct.
    private AppVisible(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisible() {
      appVisibleDepartments_ = java.util.Collections.emptyList();
      appVisiblePersons_ = java.util.Collections.emptyList();
      appVisibleTags_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisible(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                appVisibleDepartments_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment>();
                mutable_bitField0_ |= 0x00000001;
              }
              appVisibleDepartments_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                appVisiblePersons_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson>();
                mutable_bitField0_ |= 0x00000002;
              }
              appVisiblePersons_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.parser(), extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                appVisibleTags_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag>();
                mutable_bitField0_ |= 0x00000004;
              }
              appVisibleTags_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleDepartments_ = java.util.Collections.unmodifiableList(appVisibleDepartments_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          appVisiblePersons_ = java.util.Collections.unmodifiableList(appVisiblePersons_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          appVisibleTags_ = java.util.Collections.unmodifiableList(appVisibleTags_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisibleProtos.internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisibleProtos.internal_static_net_hzbox_vj_company_proto_AppVisible_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.class, net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.Builder.class);
    }

    public static final int APP_VISIBLE_DEPARTMENTS_FIELD_NUMBER = 1;
    private java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> appVisibleDepartments_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    public java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> getAppVisibleDepartmentsList() {
      return appVisibleDepartments_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    public java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder>
        getAppVisibleDepartmentsOrBuilderList() {
      return appVisibleDepartments_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    public int getAppVisibleDepartmentsCount() {
      return appVisibleDepartments_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index) {
      return appVisibleDepartments_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
        int index) {
      return appVisibleDepartments_.get(index);
    }

    public static final int APP_VISIBLE_PERSONS_FIELD_NUMBER = 2;
    private java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson> appVisiblePersons_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    public java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson> getAppVisiblePersonsList() {
      return appVisiblePersons_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    public java.util.List<? extends net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder>
        getAppVisiblePersonsOrBuilderList() {
      return appVisiblePersons_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    public int getAppVisiblePersonsCount() {
      return appVisiblePersons_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index) {
      return appVisiblePersons_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
     */
    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
        int index) {
      return appVisiblePersons_.get(index);
    }

    public static final int APP_VISIBLE_TAGS_FIELD_NUMBER = 3;
    private java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag> appVisibleTags_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    public java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag> getAppVisibleTagsList() {
      return appVisibleTags_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    public java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder>
        getAppVisibleTagsOrBuilderList() {
      return appVisibleTags_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    public int getAppVisibleTagsCount() {
      return appVisibleTags_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index) {
      return appVisibleTags_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
        int index) {
      return appVisibleTags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < appVisibleDepartments_.size(); i++) {
        output.writeMessage(1, appVisibleDepartments_.get(i));
      }
      for (int i = 0; i < appVisiblePersons_.size(); i++) {
        output.writeMessage(2, appVisiblePersons_.get(i));
      }
      for (int i = 0; i < appVisibleTags_.size(); i++) {
        output.writeMessage(3, appVisibleTags_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < appVisibleDepartments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appVisibleDepartments_.get(i));
      }
      for (int i = 0; i < appVisiblePersons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, appVisiblePersons_.get(i));
      }
      for (int i = 0; i < appVisibleTags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, appVisibleTags_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible other = (net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible) obj;

      boolean result = true;
      result = result && getAppVisibleDepartmentsList()
          .equals(other.getAppVisibleDepartmentsList());
      result = result && getAppVisiblePersonsList()
          .equals(other.getAppVisiblePersonsList());
      result = result && getAppVisibleTagsList()
          .equals(other.getAppVisibleTagsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAppVisibleDepartmentsCount() > 0) {
        hash = (37 * hash) + APP_VISIBLE_DEPARTMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisibleDepartmentsList().hashCode();
      }
      if (getAppVisiblePersonsCount() > 0) {
        hash = (37 * hash) + APP_VISIBLE_PERSONS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisiblePersonsList().hashCode();
      }
      if (getAppVisibleTagsCount() > 0) {
        hash = (37 * hash) + APP_VISIBLE_TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisibleTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisible}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisible)
        net.hzbox.vj.company.proto.AppVisibleProtos.AppVisibleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisibleProtos.internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisibleProtos.internal_static_net_hzbox_vj_company_proto_AppVisible_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.class, net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppVisibleDepartmentsFieldBuilder();
          getAppVisiblePersonsFieldBuilder();
          getAppVisibleTagsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appVisibleDepartmentsBuilder_.clear();
        }
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          appVisiblePersonsBuilder_.clear();
        }
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          appVisibleTagsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisibleProtos.internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible build() {
        net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible buildPartial() {
        net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible result = new net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible(this);
        int from_bitField0_ = bitField0_;
        if (appVisibleDepartmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            appVisibleDepartments_ = java.util.Collections.unmodifiableList(appVisibleDepartments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.appVisibleDepartments_ = appVisibleDepartments_;
        } else {
          result.appVisibleDepartments_ = appVisibleDepartmentsBuilder_.build();
        }
        if (appVisiblePersonsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            appVisiblePersons_ = java.util.Collections.unmodifiableList(appVisiblePersons_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.appVisiblePersons_ = appVisiblePersons_;
        } else {
          result.appVisiblePersons_ = appVisiblePersonsBuilder_.build();
        }
        if (appVisibleTagsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            appVisibleTags_ = java.util.Collections.unmodifiableList(appVisibleTags_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.appVisibleTags_ = appVisibleTags_;
        } else {
          result.appVisibleTags_ = appVisibleTagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible other) {
        if (other == net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible.getDefaultInstance()) return this;
        if (appVisibleDepartmentsBuilder_ == null) {
          if (!other.appVisibleDepartments_.isEmpty()) {
            if (appVisibleDepartments_.isEmpty()) {
              appVisibleDepartments_ = other.appVisibleDepartments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppVisibleDepartmentsIsMutable();
              appVisibleDepartments_.addAll(other.appVisibleDepartments_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisibleDepartments_.isEmpty()) {
            if (appVisibleDepartmentsBuilder_.isEmpty()) {
              appVisibleDepartmentsBuilder_.dispose();
              appVisibleDepartmentsBuilder_ = null;
              appVisibleDepartments_ = other.appVisibleDepartments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appVisibleDepartmentsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisibleDepartmentsFieldBuilder() : null;
            } else {
              appVisibleDepartmentsBuilder_.addAllMessages(other.appVisibleDepartments_);
            }
          }
        }
        if (appVisiblePersonsBuilder_ == null) {
          if (!other.appVisiblePersons_.isEmpty()) {
            if (appVisiblePersons_.isEmpty()) {
              appVisiblePersons_ = other.appVisiblePersons_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAppVisiblePersonsIsMutable();
              appVisiblePersons_.addAll(other.appVisiblePersons_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisiblePersons_.isEmpty()) {
            if (appVisiblePersonsBuilder_.isEmpty()) {
              appVisiblePersonsBuilder_.dispose();
              appVisiblePersonsBuilder_ = null;
              appVisiblePersons_ = other.appVisiblePersons_;
              bitField0_ = (bitField0_ & ~0x00000002);
              appVisiblePersonsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisiblePersonsFieldBuilder() : null;
            } else {
              appVisiblePersonsBuilder_.addAllMessages(other.appVisiblePersons_);
            }
          }
        }
        if (appVisibleTagsBuilder_ == null) {
          if (!other.appVisibleTags_.isEmpty()) {
            if (appVisibleTags_.isEmpty()) {
              appVisibleTags_ = other.appVisibleTags_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAppVisibleTagsIsMutable();
              appVisibleTags_.addAll(other.appVisibleTags_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisibleTags_.isEmpty()) {
            if (appVisibleTagsBuilder_.isEmpty()) {
              appVisibleTagsBuilder_.dispose();
              appVisibleTagsBuilder_ = null;
              appVisibleTags_ = other.appVisibleTags_;
              bitField0_ = (bitField0_ & ~0x00000004);
              appVisibleTagsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisibleTagsFieldBuilder() : null;
            } else {
              appVisibleTagsBuilder_.addAllMessages(other.appVisibleTags_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> appVisibleDepartments_ =
        java.util.Collections.emptyList();
      private void ensureAppVisibleDepartmentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleDepartments_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment>(appVisibleDepartments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder> appVisibleDepartmentsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> getAppVisibleDepartmentsList() {
        if (appVisibleDepartmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisibleDepartments_);
        } else {
          return appVisibleDepartmentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public int getAppVisibleDepartmentsCount() {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.size();
        } else {
          return appVisibleDepartmentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.get(index);
        } else {
          return appVisibleDepartmentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder setAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.set(index, value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder setAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder addAppVisibleDepartments(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(index, value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder addAllAppVisibleDepartments(
          Iterable<? extends net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment> values) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisibleDepartments_);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder clearAppVisibleDepartments() {
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public Builder removeAppVisibleDepartments(int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.remove(index);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder getAppVisibleDepartmentsBuilder(
          int index) {
        return getAppVisibleDepartmentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
          int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.get(index);  } else {
          return appVisibleDepartmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder>
           getAppVisibleDepartmentsOrBuilderList() {
        if (appVisibleDepartmentsBuilder_ != null) {
          return appVisibleDepartmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisibleDepartments_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder addAppVisibleDepartmentsBuilder() {
        return getAppVisibleDepartmentsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder addAppVisibleDepartmentsBuilder(
          int index) {
        return getAppVisibleDepartmentsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment app_visible_departments = 1;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder>
           getAppVisibleDepartmentsBuilderList() {
        return getAppVisibleDepartmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder>
          getAppVisibleDepartmentsFieldBuilder() {
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder>(
                  appVisibleDepartments_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          appVisibleDepartments_ = null;
        }
        return appVisibleDepartmentsBuilder_;
      }

      private java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson> appVisiblePersons_ =
        java.util.Collections.emptyList();
      private void ensureAppVisiblePersonsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          appVisiblePersons_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson>(appVisiblePersons_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder> appVisiblePersonsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson> getAppVisiblePersonsList() {
        if (appVisiblePersonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisiblePersons_);
        } else {
          return appVisiblePersonsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public int getAppVisiblePersonsCount() {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.size();
        } else {
          return appVisiblePersonsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index) {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.get(index);
        } else {
          return appVisiblePersonsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder setAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.set(index, value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder setAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder addAppVisiblePersons(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder addAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(index, value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder addAppVisiblePersons(
          net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder addAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder addAllAppVisiblePersons(
          Iterable<? extends net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson> values) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisiblePersons_);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder clearAppVisiblePersons() {
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public Builder removeAppVisiblePersons(int index) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.remove(index);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder getAppVisiblePersonsBuilder(
          int index) {
        return getAppVisiblePersonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
          int index) {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.get(index);  } else {
          return appVisiblePersonsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public java.util.List<? extends net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder>
           getAppVisiblePersonsOrBuilderList() {
        if (appVisiblePersonsBuilder_ != null) {
          return appVisiblePersonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisiblePersons_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder addAppVisiblePersonsBuilder() {
        return getAppVisiblePersonsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder addAppVisiblePersonsBuilder(
          int index) {
        return getAppVisiblePersonsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson app_visible_persons = 2;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder>
           getAppVisiblePersonsBuilderList() {
        return getAppVisiblePersonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder>
          getAppVisiblePersonsFieldBuilder() {
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder>(
                  appVisiblePersons_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          appVisiblePersons_ = null;
        }
        return appVisiblePersonsBuilder_;
      }

      private java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag> appVisibleTags_ =
        java.util.Collections.emptyList();
      private void ensureAppVisibleTagsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          appVisibleTags_ = new java.util.ArrayList<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag>(appVisibleTags_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder> appVisibleTagsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag> getAppVisibleTagsList() {
        if (appVisibleTagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisibleTags_);
        } else {
          return appVisibleTagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public int getAppVisibleTagsCount() {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.size();
        } else {
          return appVisibleTagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index) {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.get(index);
        } else {
          return appVisibleTagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder setAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.set(index, value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder setAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder addAppVisibleTags(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder addAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(index, value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder addAppVisibleTags(
          net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder addAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder addAllAppVisibleTags(
          Iterable<? extends net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag> values) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisibleTags_);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder clearAppVisibleTags() {
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          appVisibleTagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public Builder removeAppVisibleTags(int index) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.remove(index);
          onChanged();
        } else {
          appVisibleTagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder getAppVisibleTagsBuilder(
          int index) {
        return getAppVisibleTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
          int index) {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.get(index);  } else {
          return appVisibleTagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public java.util.List<? extends net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder>
           getAppVisibleTagsOrBuilderList() {
        if (appVisibleTagsBuilder_ != null) {
          return appVisibleTagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisibleTags_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder addAppVisibleTagsBuilder() {
        return getAppVisibleTagsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder addAppVisibleTagsBuilder(
          int index) {
        return getAppVisibleTagsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag app_visible_tags = 3;</code>
       */
      public java.util.List<net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder>
           getAppVisibleTagsBuilderList() {
        return getAppVisibleTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder>
          getAppVisibleTagsFieldBuilder() {
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder>(
                  appVisibleTags_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          appVisibleTags_ = null;
        }
        return appVisibleTagsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisible)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisible)
    private static final net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible();
    }

    public static net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisible>
        PARSER = new com.google.protobuf.AbstractParser<AppVisible>() {
      public AppVisible parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisible(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisible> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisible> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisibleProtos.AppVisible getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisible_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021app_visible.proto\022\032net.hzbox.vj.compan" +
      "y.proto\032\034app_visible_department.proto\032\030a" +
      "pp_visible_person.proto\032\025app_visible_tag" +
      ".proto\"\357\001\n\nAppVisible\022Q\n\027app_visible_dep" +
      "artments\030\001 \003(\01320.net.hzbox.vj.company.pr" +
      "oto.AppVisibleDepartment\022I\n\023app_visible_" +
      "persons\030\002 \003(\0132,.net.hzbox.vj.company.pro" +
      "to.AppVisiblePerson\022C\n\020app_visible_tags\030" +
      "\003 \003(\0132).net.hzbox.vj.company.proto.AppVi" +
      "sibleTagB.\n\032net.hzbox.vj.company.protoB\020",
      "AppVisibleProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.getDescriptor(),
          net.hzbox.vj.company.proto.AppVisiblePersonProtos.getDescriptor(),
          net.hzbox.vj.company.proto.AppVisibleTagProtos.getDescriptor(),
        }, assigner);
    internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_company_proto_AppVisible_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisible_descriptor,
        new String[] { "AppVisibleDepartments", "AppVisiblePersons", "AppVisibleTags", });
    net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.getDescriptor();
    net.hzbox.vj.company.proto.AppVisiblePersonProtos.getDescriptor();
    net.hzbox.vj.company.proto.AppVisibleTagProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
