// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_visible_tag.proto

package net.hzbox.vj.company.proto;

public final class AppVisibleTagProtos {
  private AppVisibleTagProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppVisibleTagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisibleTag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    int getAppId();

    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    int getAgentId();

    /**
     * <code>optional uint32 tag_id = 5;</code>
     */
    int getTagId();

    /**
     * <code>optional uint32 wechat_tag = 6;</code>
     */
    int getWechatTag();

    /**
     * <code>optional uint32 company_id = 7;</code>
     */
    int getCompanyId();

    /**
     * <code>optional string creator = 8;</code>
     */
    String getCreator();
    /**
     * <code>optional string creator = 8;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleTag}
   */
  public  static final class AppVisibleTag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisibleTag)
      AppVisibleTagOrBuilder {
    // Use AppVisibleTag.newBuilder() to construct.
    private AppVisibleTag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisibleTag() {
      id_ = 0;
      appId_ = 0;
      agentId_ = 0;
      tagId_ = 0;
      wechatTag_ = 0;
      companyId_ = 0;
      creator_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisibleTag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 24: {

              appId_ = input.readUInt32();
              break;
            }
            case 32: {

              agentId_ = input.readUInt32();
              break;
            }
            case 40: {

              tagId_ = input.readUInt32();
              break;
            }
            case 48: {

              wechatTag_ = input.readUInt32();
              break;
            }
            case 56: {

              companyId_ = input.readUInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.class, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APP_ID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int AGENT_ID_FIELD_NUMBER = 4;
    private int agentId_;
    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    public int getAgentId() {
      return agentId_;
    }

    public static final int TAG_ID_FIELD_NUMBER = 5;
    private int tagId_;
    /**
     * <code>optional uint32 tag_id = 5;</code>
     */
    public int getTagId() {
      return tagId_;
    }

    public static final int WECHAT_TAG_FIELD_NUMBER = 6;
    private int wechatTag_;
    /**
     * <code>optional uint32 wechat_tag = 6;</code>
     */
    public int getWechatTag() {
      return wechatTag_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 7;
    private int companyId_;
    /**
     * <code>optional uint32 company_id = 7;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int CREATOR_FIELD_NUMBER = 8;
    private volatile Object creator_;
    /**
     * <code>optional string creator = 8;</code>
     */
    public String getCreator() {
      Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>optional string creator = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (appId_ != 0) {
        output.writeUInt32(3, appId_);
      }
      if (agentId_ != 0) {
        output.writeUInt32(4, agentId_);
      }
      if (tagId_ != 0) {
        output.writeUInt32(5, tagId_);
      }
      if (wechatTag_ != 0) {
        output.writeUInt32(6, wechatTag_);
      }
      if (companyId_ != 0) {
        output.writeUInt32(7, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, creator_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, appId_);
      }
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, agentId_);
      }
      if (tagId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, tagId_);
      }
      if (wechatTag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, wechatTag_);
      }
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, creator_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag other = (net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getAppId()
          == other.getAppId());
      result = result && (getAgentId()
          == other.getAgentId());
      result = result && (getTagId()
          == other.getTagId());
      result = result && (getWechatTag()
          == other.getWechatTag());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && getCreator()
          .equals(other.getCreator());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (37 * hash) + TAG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTagId();
      hash = (37 * hash) + WECHAT_TAG_FIELD_NUMBER;
      hash = (53 * hash) + getWechatTag();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleTag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisibleTag)
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.class, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        appId_ = 0;

        agentId_ = 0;

        tagId_ = 0;

        wechatTag_ = 0;

        companyId_ = 0;

        creator_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag build() {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag buildPartial() {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag result = new net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag(this);
        result.id_ = id_;
        result.appId_ = appId_;
        result.agentId_ = agentId_;
        result.tagId_ = tagId_;
        result.wechatTag_ = wechatTag_;
        result.companyId_ = companyId_;
        result.creator_ = creator_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag other) {
        if (other == net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        if (other.getTagId() != 0) {
          setTagId(other.getTagId());
        }
        if (other.getWechatTag() != 0) {
          setWechatTag(other.getWechatTag());
        }
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder setAppId(int value) {

        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder clearAppId() {

        appId_ = 0;
        onChanged();
        return this;
      }

      private int agentId_ ;
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder setAgentId(int value) {

        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder clearAgentId() {

        agentId_ = 0;
        onChanged();
        return this;
      }

      private int tagId_ ;
      /**
       * <code>optional uint32 tag_id = 5;</code>
       */
      public int getTagId() {
        return tagId_;
      }
      /**
       * <code>optional uint32 tag_id = 5;</code>
       */
      public Builder setTagId(int value) {

        tagId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 tag_id = 5;</code>
       */
      public Builder clearTagId() {

        tagId_ = 0;
        onChanged();
        return this;
      }

      private int wechatTag_ ;
      /**
       * <code>optional uint32 wechat_tag = 6;</code>
       */
      public int getWechatTag() {
        return wechatTag_;
      }
      /**
       * <code>optional uint32 wechat_tag = 6;</code>
       */
      public Builder setWechatTag(int value) {

        wechatTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 wechat_tag = 6;</code>
       */
      public Builder clearWechatTag() {

        wechatTag_ = 0;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>optional uint32 company_id = 7;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional uint32 company_id = 7;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 company_id = 7;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private Object creator_ = "";
      /**
       * <code>optional string creator = 8;</code>
       */
      public String getCreator() {
        Object ref = creator_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string creator = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string creator = 8;</code>
       */
      public Builder setCreator(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 8;</code>
       */
      public Builder clearCreator() {

        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 8;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        creator_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisibleTag)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisibleTag)
    private static final net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag();
    }

    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisibleTag>
        PARSER = new com.google.protobuf.AbstractParser<AppVisibleTag>() {
      public AppVisibleTag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisibleTag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisibleTag> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisibleTag> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppVisibleTagsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisibleTags)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    java.util.List<AppVisibleTag>
        getAppVisibleTagsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    int getAppVisibleTagsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    java.util.List<? extends AppVisibleTagOrBuilder>
        getAppVisibleTagsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleTags}
   */
  public  static final class AppVisibleTags extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisibleTags)
      AppVisibleTagsOrBuilder {
    // Use AppVisibleTags.newBuilder() to construct.
    private AppVisibleTags(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisibleTags() {
      appVisibleTags_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisibleTags(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                appVisibleTags_ = new java.util.ArrayList<AppVisibleTag>();
                mutable_bitField0_ |= 0x00000001;
              }
              appVisibleTags_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleTags_ = java.util.Collections.unmodifiableList(appVisibleTags_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.class, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.Builder.class);
    }

    public static final int APPVISIBLETAGS_FIELD_NUMBER = 1;
    private java.util.List<AppVisibleTag> appVisibleTags_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    public java.util.List<AppVisibleTag> getAppVisibleTagsList() {
      return appVisibleTags_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    public java.util.List<? extends AppVisibleTagOrBuilder>
        getAppVisibleTagsOrBuilderList() {
      return appVisibleTags_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    public int getAppVisibleTagsCount() {
      return appVisibleTags_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index) {
      return appVisibleTags_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
        int index) {
      return appVisibleTags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < appVisibleTags_.size(); i++) {
        output.writeMessage(1, appVisibleTags_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < appVisibleTags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appVisibleTags_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags other = (net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags) obj;

      boolean result = true;
      result = result && getAppVisibleTagsList()
          .equals(other.getAppVisibleTagsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAppVisibleTagsCount() > 0) {
        hash = (37 * hash) + APPVISIBLETAGS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisibleTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleTags}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisibleTags)
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTags_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.class, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppVisibleTagsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appVisibleTagsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags build() {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags buildPartial() {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags result = new net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags(this);
        int from_bitField0_ = bitField0_;
        if (appVisibleTagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            appVisibleTags_ = java.util.Collections.unmodifiableList(appVisibleTags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.appVisibleTags_ = appVisibleTags_;
        } else {
          result.appVisibleTags_ = appVisibleTagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags other) {
        if (other == net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags.getDefaultInstance()) return this;
        if (appVisibleTagsBuilder_ == null) {
          if (!other.appVisibleTags_.isEmpty()) {
            if (appVisibleTags_.isEmpty()) {
              appVisibleTags_ = other.appVisibleTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppVisibleTagsIsMutable();
              appVisibleTags_.addAll(other.appVisibleTags_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisibleTags_.isEmpty()) {
            if (appVisibleTagsBuilder_.isEmpty()) {
              appVisibleTagsBuilder_.dispose();
              appVisibleTagsBuilder_ = null;
              appVisibleTags_ = other.appVisibleTags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appVisibleTagsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisibleTagsFieldBuilder() : null;
            } else {
              appVisibleTagsBuilder_.addAllMessages(other.appVisibleTags_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AppVisibleTag> appVisibleTags_ =
        java.util.Collections.emptyList();
      private void ensureAppVisibleTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleTags_ = new java.util.ArrayList<AppVisibleTag>(appVisibleTags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisibleTag, AppVisibleTag.Builder, AppVisibleTagOrBuilder> appVisibleTagsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public java.util.List<AppVisibleTag> getAppVisibleTagsList() {
        if (appVisibleTagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisibleTags_);
        } else {
          return appVisibleTagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public int getAppVisibleTagsCount() {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.size();
        } else {
          return appVisibleTagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag getAppVisibleTags(int index) {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.get(index);
        } else {
          return appVisibleTagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder setAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.set(index, value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder setAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder addAppVisibleTags(net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder addAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag value) {
        if (appVisibleTagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(index, value);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder addAppVisibleTags(
          net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder addAppVisibleTags(
          int index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder builderForValue) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleTagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder addAllAppVisibleTags(
          Iterable<? extends AppVisibleTag> values) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisibleTags_);
          onChanged();
        } else {
          appVisibleTagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder clearAppVisibleTags() {
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appVisibleTagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public Builder removeAppVisibleTags(int index) {
        if (appVisibleTagsBuilder_ == null) {
          ensureAppVisibleTagsIsMutable();
          appVisibleTags_.remove(index);
          onChanged();
        } else {
          appVisibleTagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder getAppVisibleTagsBuilder(
          int index) {
        return getAppVisibleTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTagOrBuilder getAppVisibleTagsOrBuilder(
          int index) {
        if (appVisibleTagsBuilder_ == null) {
          return appVisibleTags_.get(index);  } else {
          return appVisibleTagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public java.util.List<? extends AppVisibleTagOrBuilder>
           getAppVisibleTagsOrBuilderList() {
        if (appVisibleTagsBuilder_ != null) {
          return appVisibleTagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisibleTags_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder addAppVisibleTagsBuilder() {
        return getAppVisibleTagsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.Builder addAppVisibleTagsBuilder(
          int index) {
        return getAppVisibleTagsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTag.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleTag appVisibleTags = 1;</code>
       */
      public java.util.List<AppVisibleTag.Builder>
           getAppVisibleTagsBuilderList() {
        return getAppVisibleTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisibleTag, AppVisibleTag.Builder, AppVisibleTagOrBuilder>
          getAppVisibleTagsFieldBuilder() {
        if (appVisibleTagsBuilder_ == null) {
          appVisibleTagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AppVisibleTag, AppVisibleTag.Builder, AppVisibleTagOrBuilder>(
                  appVisibleTags_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          appVisibleTags_ = null;
        }
        return appVisibleTagsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisibleTags)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisibleTags)
    private static final net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags();
    }

    public static net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisibleTags>
        PARSER = new com.google.protobuf.AbstractParser<AppVisibleTags>() {
      public AppVisibleTags parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisibleTags(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisibleTags> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisibleTags> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisibleTagProtos.AppVisibleTags getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisibleTag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisibleTags_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025app_visible_tag.proto\022\032net.hzbox.vj.co" +
      "mpany.proto\"\206\001\n\rAppVisibleTag\022\n\n\002id\030\001 \001(" +
      "\r\022\016\n\006app_id\030\003 \001(\r\022\020\n\010agent_id\030\004 \001(\r\022\016\n\006t" +
      "ag_id\030\005 \001(\r\022\022\n\nwechat_tag\030\006 \001(\r\022\022\n\ncompa" +
      "ny_id\030\007 \001(\r\022\017\n\007creator\030\010 \001(\t\"S\n\016AppVisib" +
      "leTags\022A\n\016appVisibleTags\030\001 \003(\0132).net.hzb" +
      "ox.vj.company.proto.AppVisibleTagB1\n\032net" +
      ".hzbox.vj.company.protoB\023AppVisibleTagPr" +
      "otosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_company_proto_AppVisibleTag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisibleTag_descriptor,
        new String[] { "Id", "AppId", "AgentId", "TagId", "WechatTag", "CompanyId", "Creator", });
    internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_hzbox_vj_company_proto_AppVisibleTags_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisibleTags_descriptor,
        new String[] { "AppVisibleTags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
