// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_visible_person.proto

package net.hzbox.vj.company.proto;

public final class AppVisiblePersonProtos {
  private AppVisiblePersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppVisiblePersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisiblePerson)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    int getAppId();

    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    int getAgentId();

    /**
     * <code>optional string account = 5;</code>
     */
    String getAccount();
    /**
     * <code>optional string account = 5;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional uint32 company_id = 6;</code>
     */
    int getCompanyId();

    /**
     * <code>optional string creator = 7;</code>
     */
    String getCreator();
    /**
     * <code>optional string creator = 7;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <code>optional uint32 person_id = 8;</code>
     */
    int getPersonId();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisiblePerson}
   */
  public  static final class AppVisiblePerson extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisiblePerson)
      AppVisiblePersonOrBuilder {
    // Use AppVisiblePerson.newBuilder() to construct.
    private AppVisiblePerson(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisiblePerson() {
      id_ = 0;
      appId_ = 0;
      agentId_ = 0;
      account_ = "";
      companyId_ = 0;
      creator_ = "";
      personId_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisiblePerson(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 24: {

              appId_ = input.readUInt32();
              break;
            }
            case 32: {

              agentId_ = input.readUInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 48: {

              companyId_ = input.readUInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
            case 64: {

              personId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.class, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APP_ID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int AGENT_ID_FIELD_NUMBER = 4;
    private int agentId_;
    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    public int getAgentId() {
      return agentId_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 5;
    private volatile Object account_;
    /**
     * <code>optional string account = 5;</code>
     */
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>optional string account = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 6;
    private int companyId_;
    /**
     * <code>optional uint32 company_id = 6;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int CREATOR_FIELD_NUMBER = 7;
    private volatile Object creator_;
    /**
     * <code>optional string creator = 7;</code>
     */
    public String getCreator() {
      Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>optional string creator = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_ID_FIELD_NUMBER = 8;
    private int personId_;
    /**
     * <code>optional uint32 person_id = 8;</code>
     */
    public int getPersonId() {
      return personId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (appId_ != 0) {
        output.writeUInt32(3, appId_);
      }
      if (agentId_ != 0) {
        output.writeUInt32(4, agentId_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, account_);
      }
      if (companyId_ != 0) {
        output.writeUInt32(6, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, creator_);
      }
      if (personId_ != 0) {
        output.writeUInt32(8, personId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, appId_);
      }
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, agentId_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, account_);
      }
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, creator_);
      }
      if (personId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, personId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson other = (net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getAppId()
          == other.getAppId());
      result = result && (getAgentId()
          == other.getAgentId());
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && getCreator()
          .equals(other.getCreator());
      result = result && (getPersonId()
          == other.getPersonId());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisiblePerson}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisiblePerson)
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.class, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        appId_ = 0;

        agentId_ = 0;

        account_ = "";

        companyId_ = 0;

        creator_ = "";

        personId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson build() {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson buildPartial() {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson result = new net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson(this);
        result.id_ = id_;
        result.appId_ = appId_;
        result.agentId_ = agentId_;
        result.account_ = account_;
        result.companyId_ = companyId_;
        result.creator_ = creator_;
        result.personId_ = personId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson other) {
        if (other == net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        if (other.getPersonId() != 0) {
          setPersonId(other.getPersonId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder setAppId(int value) {

        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder clearAppId() {

        appId_ = 0;
        onChanged();
        return this;
      }

      private int agentId_ ;
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder setAgentId(int value) {

        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder clearAgentId() {

        agentId_ = 0;
        onChanged();
        return this;
      }

      private Object account_ = "";
      /**
       * <code>optional string account = 5;</code>
       */
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string account = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 5;</code>
       */
      public Builder setAccount(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 5;</code>
       */
      public Builder clearAccount() {

        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 5;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        account_ = value;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>optional uint32 company_id = 6;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional uint32 company_id = 6;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 company_id = 6;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private Object creator_ = "";
      /**
       * <code>optional string creator = 7;</code>
       */
      public String getCreator() {
        Object ref = creator_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string creator = 7;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string creator = 7;</code>
       */
      public Builder setCreator(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 7;</code>
       */
      public Builder clearCreator() {

        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 7;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        creator_ = value;
        onChanged();
        return this;
      }

      private int personId_ ;
      /**
       * <code>optional uint32 person_id = 8;</code>
       */
      public int getPersonId() {
        return personId_;
      }
      /**
       * <code>optional uint32 person_id = 8;</code>
       */
      public Builder setPersonId(int value) {

        personId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 person_id = 8;</code>
       */
      public Builder clearPersonId() {

        personId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisiblePerson)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisiblePerson)
    private static final net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson();
    }

    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisiblePerson>
        PARSER = new com.google.protobuf.AbstractParser<AppVisiblePerson>() {
      public AppVisiblePerson parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisiblePerson(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisiblePerson> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisiblePerson> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppVisiblePersonsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisiblePersons)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    java.util.List<AppVisiblePerson>
        getAppVisiblePersonsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    int getAppVisiblePersonsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    java.util.List<? extends AppVisiblePersonOrBuilder>
        getAppVisiblePersonsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
            int index);

    /**
     * <code>optional uint32 total_count = 2;</code>
     */
    int getTotalCount();

    /**
     * <code>optional uint32 total_pages = 3;</code>
     */
    int getTotalPages();

    /**
     * <code>optional uint32 page = 4;</code>
     */
    int getPage();

    /**
     * <code>optional uint32 size = 5;</code>
     */
    int getSize();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisiblePersons}
   */
  public  static final class AppVisiblePersons extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisiblePersons)
      AppVisiblePersonsOrBuilder {
    // Use AppVisiblePersons.newBuilder() to construct.
    private AppVisiblePersons(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisiblePersons() {
      appVisiblePersons_ = java.util.Collections.emptyList();
      totalCount_ = 0;
      totalPages_ = 0;
      page_ = 0;
      size_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisiblePersons(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                appVisiblePersons_ = new java.util.ArrayList<AppVisiblePerson>();
                mutable_bitField0_ |= 0x00000001;
              }
              appVisiblePersons_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.parser(), extensionRegistry));
              break;
            }
            case 16: {

              totalCount_ = input.readUInt32();
              break;
            }
            case 24: {

              totalPages_ = input.readUInt32();
              break;
            }
            case 32: {

              page_ = input.readUInt32();
              break;
            }
            case 40: {

              size_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          appVisiblePersons_ = java.util.Collections.unmodifiableList(appVisiblePersons_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.class, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.Builder.class);
    }

    private int bitField0_;
    public static final int APPVISIBLEPERSONS_FIELD_NUMBER = 1;
    private java.util.List<AppVisiblePerson> appVisiblePersons_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    public java.util.List<AppVisiblePerson> getAppVisiblePersonsList() {
      return appVisiblePersons_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    public java.util.List<? extends AppVisiblePersonOrBuilder>
        getAppVisiblePersonsOrBuilderList() {
      return appVisiblePersons_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    public int getAppVisiblePersonsCount() {
      return appVisiblePersons_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index) {
      return appVisiblePersons_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
        int index) {
      return appVisiblePersons_.get(index);
    }

    public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
    private int totalCount_;
    /**
     * <code>optional uint32 total_count = 2;</code>
     */
    public int getTotalCount() {
      return totalCount_;
    }

    public static final int TOTAL_PAGES_FIELD_NUMBER = 3;
    private int totalPages_;
    /**
     * <code>optional uint32 total_pages = 3;</code>
     */
    public int getTotalPages() {
      return totalPages_;
    }

    public static final int PAGE_FIELD_NUMBER = 4;
    private int page_;
    /**
     * <code>optional uint32 page = 4;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private int size_;
    /**
     * <code>optional uint32 size = 5;</code>
     */
    public int getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < appVisiblePersons_.size(); i++) {
        output.writeMessage(1, appVisiblePersons_.get(i));
      }
      if (totalCount_ != 0) {
        output.writeUInt32(2, totalCount_);
      }
      if (totalPages_ != 0) {
        output.writeUInt32(3, totalPages_);
      }
      if (page_ != 0) {
        output.writeUInt32(4, page_);
      }
      if (size_ != 0) {
        output.writeUInt32(5, size_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < appVisiblePersons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appVisiblePersons_.get(i));
      }
      if (totalCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, totalCount_);
      }
      if (totalPages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, totalPages_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, page_);
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, size_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons other = (net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons) obj;

      boolean result = true;
      result = result && getAppVisiblePersonsList()
          .equals(other.getAppVisiblePersonsList());
      result = result && (getTotalCount()
          == other.getTotalCount());
      result = result && (getTotalPages()
          == other.getTotalPages());
      result = result && (getPage()
          == other.getPage());
      result = result && (getSize()
          == other.getSize());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAppVisiblePersonsCount() > 0) {
        hash = (37 * hash) + APPVISIBLEPERSONS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisiblePersonsList().hashCode();
      }
      hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCount();
      hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPages();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisiblePersons}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisiblePersons)
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.class, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppVisiblePersonsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appVisiblePersonsBuilder_.clear();
        }
        totalCount_ = 0;

        totalPages_ = 0;

        page_ = 0;

        size_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons build() {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons buildPartial() {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons result = new net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (appVisiblePersonsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            appVisiblePersons_ = java.util.Collections.unmodifiableList(appVisiblePersons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.appVisiblePersons_ = appVisiblePersons_;
        } else {
          result.appVisiblePersons_ = appVisiblePersonsBuilder_.build();
        }
        result.totalCount_ = totalCount_;
        result.totalPages_ = totalPages_;
        result.page_ = page_;
        result.size_ = size_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons other) {
        if (other == net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons.getDefaultInstance()) return this;
        if (appVisiblePersonsBuilder_ == null) {
          if (!other.appVisiblePersons_.isEmpty()) {
            if (appVisiblePersons_.isEmpty()) {
              appVisiblePersons_ = other.appVisiblePersons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppVisiblePersonsIsMutable();
              appVisiblePersons_.addAll(other.appVisiblePersons_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisiblePersons_.isEmpty()) {
            if (appVisiblePersonsBuilder_.isEmpty()) {
              appVisiblePersonsBuilder_.dispose();
              appVisiblePersonsBuilder_ = null;
              appVisiblePersons_ = other.appVisiblePersons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appVisiblePersonsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisiblePersonsFieldBuilder() : null;
            } else {
              appVisiblePersonsBuilder_.addAllMessages(other.appVisiblePersons_);
            }
          }
        }
        if (other.getTotalCount() != 0) {
          setTotalCount(other.getTotalCount());
        }
        if (other.getTotalPages() != 0) {
          setTotalPages(other.getTotalPages());
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AppVisiblePerson> appVisiblePersons_ =
        java.util.Collections.emptyList();
      private void ensureAppVisiblePersonsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          appVisiblePersons_ = new java.util.ArrayList<AppVisiblePerson>(appVisiblePersons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisiblePerson, AppVisiblePerson.Builder, AppVisiblePersonOrBuilder> appVisiblePersonsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public java.util.List<AppVisiblePerson> getAppVisiblePersonsList() {
        if (appVisiblePersonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisiblePersons_);
        } else {
          return appVisiblePersonsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public int getAppVisiblePersonsCount() {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.size();
        } else {
          return appVisiblePersonsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson getAppVisiblePersons(int index) {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.get(index);
        } else {
          return appVisiblePersonsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder setAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.set(index, value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder setAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder addAppVisiblePersons(net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder addAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson value) {
        if (appVisiblePersonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(index, value);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder addAppVisiblePersons(
          net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder addAppVisiblePersons(
          int index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder builderForValue) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder addAllAppVisiblePersons(
          Iterable<? extends AppVisiblePerson> values) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisiblePersons_);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder clearAppVisiblePersons() {
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public Builder removeAppVisiblePersons(int index) {
        if (appVisiblePersonsBuilder_ == null) {
          ensureAppVisiblePersonsIsMutable();
          appVisiblePersons_.remove(index);
          onChanged();
        } else {
          appVisiblePersonsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder getAppVisiblePersonsBuilder(
          int index) {
        return getAppVisiblePersonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersonOrBuilder getAppVisiblePersonsOrBuilder(
          int index) {
        if (appVisiblePersonsBuilder_ == null) {
          return appVisiblePersons_.get(index);  } else {
          return appVisiblePersonsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public java.util.List<? extends AppVisiblePersonOrBuilder>
           getAppVisiblePersonsOrBuilderList() {
        if (appVisiblePersonsBuilder_ != null) {
          return appVisiblePersonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisiblePersons_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder addAppVisiblePersonsBuilder() {
        return getAppVisiblePersonsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.Builder addAppVisiblePersonsBuilder(
          int index) {
        return getAppVisiblePersonsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePerson.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisiblePerson appVisiblePersons = 1;</code>
       */
      public java.util.List<AppVisiblePerson.Builder>
           getAppVisiblePersonsBuilderList() {
        return getAppVisiblePersonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisiblePerson, AppVisiblePerson.Builder, AppVisiblePersonOrBuilder>
          getAppVisiblePersonsFieldBuilder() {
        if (appVisiblePersonsBuilder_ == null) {
          appVisiblePersonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AppVisiblePerson, AppVisiblePerson.Builder, AppVisiblePersonOrBuilder>(
                  appVisiblePersons_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          appVisiblePersons_ = null;
        }
        return appVisiblePersonsBuilder_;
      }

      private int totalCount_ ;
      /**
       * <code>optional uint32 total_count = 2;</code>
       */
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <code>optional uint32 total_count = 2;</code>
       */
      public Builder setTotalCount(int value) {

        totalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 total_count = 2;</code>
       */
      public Builder clearTotalCount() {

        totalCount_ = 0;
        onChanged();
        return this;
      }

      private int totalPages_ ;
      /**
       * <code>optional uint32 total_pages = 3;</code>
       */
      public int getTotalPages() {
        return totalPages_;
      }
      /**
       * <code>optional uint32 total_pages = 3;</code>
       */
      public Builder setTotalPages(int value) {

        totalPages_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 total_pages = 3;</code>
       */
      public Builder clearTotalPages() {

        totalPages_ = 0;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>optional uint32 page = 4;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional uint32 page = 4;</code>
       */
      public Builder setPage(int value) {

        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 page = 4;</code>
       */
      public Builder clearPage() {

        page_ = 0;
        onChanged();
        return this;
      }

      private int size_ ;
      /**
       * <code>optional uint32 size = 5;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>optional uint32 size = 5;</code>
       */
      public Builder setSize(int value) {

        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 size = 5;</code>
       */
      public Builder clearSize() {

        size_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisiblePersons)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisiblePersons)
    private static final net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons();
    }

    public static net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisiblePersons>
        PARSER = new com.google.protobuf.AbstractParser<AppVisiblePersons>() {
      public AppVisiblePersons parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisiblePersons(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisiblePersons> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisiblePersons> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisiblePersonProtos.AppVisiblePersons getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030app_visible_person.proto\022\032net.hzbox.vj" +
      ".company.proto\"\211\001\n\020AppVisiblePerson\022\n\n\002i" +
      "d\030\001 \001(\r\022\016\n\006app_id\030\003 \001(\r\022\020\n\010agent_id\030\004 \001(" +
      "\r\022\017\n\007account\030\005 \001(\t\022\022\n\ncompany_id\030\006 \001(\r\022\017" +
      "\n\007creator\030\007 \001(\t\022\021\n\tperson_id\030\010 \001(\r\"\242\001\n\021A" +
      "ppVisiblePersons\022G\n\021appVisiblePersons\030\001 " +
      "\003(\0132,.net.hzbox.vj.company.proto.AppVisi" +
      "blePerson\022\023\n\013total_count\030\002 \001(\r\022\023\n\013total_" +
      "pages\030\003 \001(\r\022\014\n\004page\030\004 \001(\r\022\014\n\004size\030\005 \001(\rB" +
      "4\n\032net.hzbox.vj.company.protoB\026AppVisibl",
      "ePersonProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisiblePerson_descriptor,
        new String[] { "Id", "AppId", "AgentId", "Account", "CompanyId", "Creator", "PersonId", });
    internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisiblePersons_descriptor,
        new String[] { "AppVisiblePersons", "TotalCount", "TotalPages", "Page", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
