// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_visible_department.proto

package net.hzbox.vj.company.proto;

public final class AppVisibleDepartmentProtos {
  private AppVisibleDepartmentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppVisibleDepartmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisibleDepartment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    int getAppId();

    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    int getAgentId();

    /**
     * <code>optional uint32 wechat_department = 5;</code>
     */
    int getWechatDepartment();

    /**
     * <code>optional uint32 deparment_id = 6;</code>
     */
    int getDeparmentId();

    /**
     * <code>optional uint32 has_parent = 7;</code>
     */
    int getHasParent();

    /**
     * <code>optional uint32 has_child = 8;</code>
     */
    int getHasChild();

    /**
     * <code>optional uint32 company_id = 9;</code>
     */
    int getCompanyId();

    /**
     * <code>optional string creator = 10;</code>
     */
    String getCreator();
    /**
     * <code>optional string creator = 10;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleDepartment}
   */
  public  static final class AppVisibleDepartment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisibleDepartment)
      AppVisibleDepartmentOrBuilder {
    // Use AppVisibleDepartment.newBuilder() to construct.
    private AppVisibleDepartment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisibleDepartment() {
      id_ = 0;
      appId_ = 0;
      agentId_ = 0;
      wechatDepartment_ = 0;
      deparmentId_ = 0;
      hasParent_ = 0;
      hasChild_ = 0;
      companyId_ = 0;
      creator_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisibleDepartment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 24: {

              appId_ = input.readUInt32();
              break;
            }
            case 32: {

              agentId_ = input.readUInt32();
              break;
            }
            case 40: {

              wechatDepartment_ = input.readUInt32();
              break;
            }
            case 48: {

              deparmentId_ = input.readUInt32();
              break;
            }
            case 56: {

              hasParent_ = input.readUInt32();
              break;
            }
            case 64: {

              hasChild_ = input.readUInt32();
              break;
            }
            case 72: {

              companyId_ = input.readUInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              creator_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.class, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APP_ID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <code>optional uint32 app_id = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int AGENT_ID_FIELD_NUMBER = 4;
    private int agentId_;
    /**
     * <code>optional uint32 agent_id = 4;</code>
     */
    public int getAgentId() {
      return agentId_;
    }

    public static final int WECHAT_DEPARTMENT_FIELD_NUMBER = 5;
    private int wechatDepartment_;
    /**
     * <code>optional uint32 wechat_department = 5;</code>
     */
    public int getWechatDepartment() {
      return wechatDepartment_;
    }

    public static final int DEPARMENT_ID_FIELD_NUMBER = 6;
    private int deparmentId_;
    /**
     * <code>optional uint32 deparment_id = 6;</code>
     */
    public int getDeparmentId() {
      return deparmentId_;
    }

    public static final int HAS_PARENT_FIELD_NUMBER = 7;
    private int hasParent_;
    /**
     * <code>optional uint32 has_parent = 7;</code>
     */
    public int getHasParent() {
      return hasParent_;
    }

    public static final int HAS_CHILD_FIELD_NUMBER = 8;
    private int hasChild_;
    /**
     * <code>optional uint32 has_child = 8;</code>
     */
    public int getHasChild() {
      return hasChild_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 9;
    private int companyId_;
    /**
     * <code>optional uint32 company_id = 9;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int CREATOR_FIELD_NUMBER = 10;
    private volatile Object creator_;
    /**
     * <code>optional string creator = 10;</code>
     */
    public String getCreator() {
      Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        creator_ = s;
        return s;
      }
    }
    /**
     * <code>optional string creator = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (appId_ != 0) {
        output.writeUInt32(3, appId_);
      }
      if (agentId_ != 0) {
        output.writeUInt32(4, agentId_);
      }
      if (wechatDepartment_ != 0) {
        output.writeUInt32(5, wechatDepartment_);
      }
      if (deparmentId_ != 0) {
        output.writeUInt32(6, deparmentId_);
      }
      if (hasParent_ != 0) {
        output.writeUInt32(7, hasParent_);
      }
      if (hasChild_ != 0) {
        output.writeUInt32(8, hasChild_);
      }
      if (companyId_ != 0) {
        output.writeUInt32(9, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, creator_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, appId_);
      }
      if (agentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, agentId_);
      }
      if (wechatDepartment_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, wechatDepartment_);
      }
      if (deparmentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, deparmentId_);
      }
      if (hasParent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, hasParent_);
      }
      if (hasChild_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, hasChild_);
      }
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, companyId_);
      }
      if (!getCreatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, creator_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment other = (net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getAppId()
          == other.getAppId());
      result = result && (getAgentId()
          == other.getAgentId());
      result = result && (getWechatDepartment()
          == other.getWechatDepartment());
      result = result && (getDeparmentId()
          == other.getDeparmentId());
      result = result && (getHasParent()
          == other.getHasParent());
      result = result && (getHasChild()
          == other.getHasChild());
      result = result && (getCompanyId()
          == other.getCompanyId());
      result = result && getCreator()
          .equals(other.getCreator());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId();
      hash = (37 * hash) + WECHAT_DEPARTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getWechatDepartment();
      hash = (37 * hash) + DEPARMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeparmentId();
      hash = (37 * hash) + HAS_PARENT_FIELD_NUMBER;
      hash = (53 * hash) + getHasParent();
      hash = (37 * hash) + HAS_CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getHasChild();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + CREATOR_FIELD_NUMBER;
      hash = (53 * hash) + getCreator().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleDepartment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisibleDepartment)
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.class, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        appId_ = 0;

        agentId_ = 0;

        wechatDepartment_ = 0;

        deparmentId_ = 0;

        hasParent_ = 0;

        hasChild_ = 0;

        companyId_ = 0;

        creator_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment build() {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment buildPartial() {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment result = new net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment(this);
        result.id_ = id_;
        result.appId_ = appId_;
        result.agentId_ = agentId_;
        result.wechatDepartment_ = wechatDepartment_;
        result.deparmentId_ = deparmentId_;
        result.hasParent_ = hasParent_;
        result.hasChild_ = hasChild_;
        result.companyId_ = companyId_;
        result.creator_ = creator_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment other) {
        if (other == net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getAgentId() != 0) {
          setAgentId(other.getAgentId());
        }
        if (other.getWechatDepartment() != 0) {
          setWechatDepartment(other.getWechatDepartment());
        }
        if (other.getDeparmentId() != 0) {
          setDeparmentId(other.getDeparmentId());
        }
        if (other.getHasParent() != 0) {
          setHasParent(other.getHasParent());
        }
        if (other.getHasChild() != 0) {
          setHasChild(other.getHasChild());
        }
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (!other.getCreator().isEmpty()) {
          creator_ = other.creator_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder setAppId(int value) {

        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 app_id = 3;</code>
       */
      public Builder clearAppId() {

        appId_ = 0;
        onChanged();
        return this;
      }

      private int agentId_ ;
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public int getAgentId() {
        return agentId_;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder setAgentId(int value) {

        agentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 agent_id = 4;</code>
       */
      public Builder clearAgentId() {

        agentId_ = 0;
        onChanged();
        return this;
      }

      private int wechatDepartment_ ;
      /**
       * <code>optional uint32 wechat_department = 5;</code>
       */
      public int getWechatDepartment() {
        return wechatDepartment_;
      }
      /**
       * <code>optional uint32 wechat_department = 5;</code>
       */
      public Builder setWechatDepartment(int value) {

        wechatDepartment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 wechat_department = 5;</code>
       */
      public Builder clearWechatDepartment() {

        wechatDepartment_ = 0;
        onChanged();
        return this;
      }

      private int deparmentId_ ;
      /**
       * <code>optional uint32 deparment_id = 6;</code>
       */
      public int getDeparmentId() {
        return deparmentId_;
      }
      /**
       * <code>optional uint32 deparment_id = 6;</code>
       */
      public Builder setDeparmentId(int value) {

        deparmentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 deparment_id = 6;</code>
       */
      public Builder clearDeparmentId() {

        deparmentId_ = 0;
        onChanged();
        return this;
      }

      private int hasParent_ ;
      /**
       * <code>optional uint32 has_parent = 7;</code>
       */
      public int getHasParent() {
        return hasParent_;
      }
      /**
       * <code>optional uint32 has_parent = 7;</code>
       */
      public Builder setHasParent(int value) {

        hasParent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 has_parent = 7;</code>
       */
      public Builder clearHasParent() {

        hasParent_ = 0;
        onChanged();
        return this;
      }

      private int hasChild_ ;
      /**
       * <code>optional uint32 has_child = 8;</code>
       */
      public int getHasChild() {
        return hasChild_;
      }
      /**
       * <code>optional uint32 has_child = 8;</code>
       */
      public Builder setHasChild(int value) {

        hasChild_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 has_child = 8;</code>
       */
      public Builder clearHasChild() {

        hasChild_ = 0;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>optional uint32 company_id = 9;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional uint32 company_id = 9;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 company_id = 9;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private Object creator_ = "";
      /**
       * <code>optional string creator = 10;</code>
       */
      public String getCreator() {
        Object ref = creator_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string creator = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string creator = 10;</code>
       */
      public Builder setCreator(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 10;</code>
       */
      public Builder clearCreator() {

        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 10;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        creator_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisibleDepartment)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisibleDepartment)
    private static final net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment();
    }

    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisibleDepartment>
        PARSER = new com.google.protobuf.AbstractParser<AppVisibleDepartment>() {
      public AppVisibleDepartment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisibleDepartment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisibleDepartment> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisibleDepartment> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppVisibleDepartmentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.hzbox.vj.company.proto.AppVisibleDepartments)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    java.util.List<AppVisibleDepartment>
        getAppVisibleDepartmentsList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index);
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    int getAppVisibleDepartmentsCount();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    java.util.List<? extends AppVisibleDepartmentOrBuilder>
        getAppVisibleDepartmentsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleDepartments}
   */
  public  static final class AppVisibleDepartments extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:net.hzbox.vj.company.proto.AppVisibleDepartments)
      AppVisibleDepartmentsOrBuilder {
    // Use AppVisibleDepartments.newBuilder() to construct.
    private AppVisibleDepartments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppVisibleDepartments() {
      appVisibleDepartments_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppVisibleDepartments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                appVisibleDepartments_ = new java.util.ArrayList<AppVisibleDepartment>();
                mutable_bitField0_ |= 0x00000001;
              }
              appVisibleDepartments_.add(
                  input.readMessage(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleDepartments_ = java.util.Collections.unmodifiableList(appVisibleDepartments_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.class, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.Builder.class);
    }

    public static final int APPVISIBLEDEPARTMENTS_FIELD_NUMBER = 1;
    private java.util.List<AppVisibleDepartment> appVisibleDepartments_;
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    public java.util.List<AppVisibleDepartment> getAppVisibleDepartmentsList() {
      return appVisibleDepartments_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    public java.util.List<? extends AppVisibleDepartmentOrBuilder>
        getAppVisibleDepartmentsOrBuilderList() {
      return appVisibleDepartments_;
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    public int getAppVisibleDepartmentsCount() {
      return appVisibleDepartments_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index) {
      return appVisibleDepartments_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
     */
    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
        int index) {
      return appVisibleDepartments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < appVisibleDepartments_.size(); i++) {
        output.writeMessage(1, appVisibleDepartments_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < appVisibleDepartments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, appVisibleDepartments_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments)) {
        return super.equals(obj);
      }
      net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments other = (net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments) obj;

      boolean result = true;
      result = result && getAppVisibleDepartmentsList()
          .equals(other.getAppVisibleDepartmentsList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAppVisibleDepartmentsCount() > 0) {
        hash = (37 * hash) + APPVISIBLEDEPARTMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAppVisibleDepartmentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.company.proto.AppVisibleDepartments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.hzbox.vj.company.proto.AppVisibleDepartments)
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.class, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.Builder.class);
      }

      // Construct using net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppVisibleDepartmentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appVisibleDepartmentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor;
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments getDefaultInstanceForType() {
        return net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.getDefaultInstance();
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments build() {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments buildPartial() {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments result = new net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments(this);
        int from_bitField0_ = bitField0_;
        if (appVisibleDepartmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            appVisibleDepartments_ = java.util.Collections.unmodifiableList(appVisibleDepartments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.appVisibleDepartments_ = appVisibleDepartments_;
        } else {
          result.appVisibleDepartments_ = appVisibleDepartmentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments) {
          return mergeFrom((net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments other) {
        if (other == net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments.getDefaultInstance()) return this;
        if (appVisibleDepartmentsBuilder_ == null) {
          if (!other.appVisibleDepartments_.isEmpty()) {
            if (appVisibleDepartments_.isEmpty()) {
              appVisibleDepartments_ = other.appVisibleDepartments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppVisibleDepartmentsIsMutable();
              appVisibleDepartments_.addAll(other.appVisibleDepartments_);
            }
            onChanged();
          }
        } else {
          if (!other.appVisibleDepartments_.isEmpty()) {
            if (appVisibleDepartmentsBuilder_.isEmpty()) {
              appVisibleDepartmentsBuilder_.dispose();
              appVisibleDepartmentsBuilder_ = null;
              appVisibleDepartments_ = other.appVisibleDepartments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appVisibleDepartmentsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppVisibleDepartmentsFieldBuilder() : null;
            } else {
              appVisibleDepartmentsBuilder_.addAllMessages(other.appVisibleDepartments_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<AppVisibleDepartment> appVisibleDepartments_ =
        java.util.Collections.emptyList();
      private void ensureAppVisibleDepartmentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          appVisibleDepartments_ = new java.util.ArrayList<AppVisibleDepartment>(appVisibleDepartments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisibleDepartment, AppVisibleDepartment.Builder, AppVisibleDepartmentOrBuilder> appVisibleDepartmentsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public java.util.List<AppVisibleDepartment> getAppVisibleDepartmentsList() {
        if (appVisibleDepartmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(appVisibleDepartments_);
        } else {
          return appVisibleDepartmentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public int getAppVisibleDepartmentsCount() {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.size();
        } else {
          return appVisibleDepartmentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment getAppVisibleDepartments(int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.get(index);
        } else {
          return appVisibleDepartmentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder setAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.set(index, value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder setAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.set(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder addAppVisibleDepartments(net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment value) {
        if (appVisibleDepartmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(index, value);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder addAppVisibleDepartments(
          int index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder builderForValue) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.add(index, builderForValue.build());
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder addAllAppVisibleDepartments(
          Iterable<? extends AppVisibleDepartment> values) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, appVisibleDepartments_);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder clearAppVisibleDepartments() {
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public Builder removeAppVisibleDepartments(int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          ensureAppVisibleDepartmentsIsMutable();
          appVisibleDepartments_.remove(index);
          onChanged();
        } else {
          appVisibleDepartmentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder getAppVisibleDepartmentsBuilder(
          int index) {
        return getAppVisibleDepartmentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartmentOrBuilder getAppVisibleDepartmentsOrBuilder(
          int index) {
        if (appVisibleDepartmentsBuilder_ == null) {
          return appVisibleDepartments_.get(index);  } else {
          return appVisibleDepartmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public java.util.List<? extends AppVisibleDepartmentOrBuilder>
           getAppVisibleDepartmentsOrBuilderList() {
        if (appVisibleDepartmentsBuilder_ != null) {
          return appVisibleDepartmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(appVisibleDepartments_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder addAppVisibleDepartmentsBuilder() {
        return getAppVisibleDepartmentsFieldBuilder().addBuilder(
            net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.Builder addAppVisibleDepartmentsBuilder(
          int index) {
        return getAppVisibleDepartmentsFieldBuilder().addBuilder(
            index, net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartment.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.company.proto.AppVisibleDepartment appVisibleDepartments = 1;</code>
       */
      public java.util.List<AppVisibleDepartment.Builder>
           getAppVisibleDepartmentsBuilderList() {
        return getAppVisibleDepartmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AppVisibleDepartment, AppVisibleDepartment.Builder, AppVisibleDepartmentOrBuilder>
          getAppVisibleDepartmentsFieldBuilder() {
        if (appVisibleDepartmentsBuilder_ == null) {
          appVisibleDepartmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AppVisibleDepartment, AppVisibleDepartment.Builder, AppVisibleDepartmentOrBuilder>(
                  appVisibleDepartments_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          appVisibleDepartments_ = null;
        }
        return appVisibleDepartmentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.company.proto.AppVisibleDepartments)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.company.proto.AppVisibleDepartments)
    private static final net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments();
    }

    public static net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppVisibleDepartments>
        PARSER = new com.google.protobuf.AbstractParser<AppVisibleDepartments>() {
      public AppVisibleDepartments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppVisibleDepartments(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppVisibleDepartments> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppVisibleDepartments> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.company.proto.AppVisibleDepartmentProtos.AppVisibleDepartments getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034app_visible_department.proto\022\032net.hzbo" +
      "x.vj.company.proto\"\301\001\n\024AppVisibleDepartm" +
      "ent\022\n\n\002id\030\001 \001(\r\022\016\n\006app_id\030\003 \001(\r\022\020\n\010agent" +
      "_id\030\004 \001(\r\022\031\n\021wechat_department\030\005 \001(\r\022\024\n\014" +
      "deparment_id\030\006 \001(\r\022\022\n\nhas_parent\030\007 \001(\r\022\021" +
      "\n\thas_child\030\010 \001(\r\022\022\n\ncompany_id\030\t \001(\r\022\017\n" +
      "\007creator\030\n \001(\t\"h\n\025AppVisibleDepartments\022" +
      "O\n\025appVisibleDepartments\030\001 \003(\01320.net.hzb" +
      "ox.vj.company.proto.AppVisibleDepartment" +
      "B8\n\032net.hzbox.vj.company.protoB\032AppVisib",
      "leDepartmentProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisibleDepartment_descriptor,
        new String[] { "Id", "AppId", "AgentId", "WechatDepartment", "DeparmentId", "HasParent", "HasChild", "CompanyId", "Creator", });
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_hzbox_vj_company_proto_AppVisibleDepartments_descriptor,
        new String[] { "AppVisibleDepartments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
