// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wechat_msg.proto

package net.hzbox.vj.manager.proto;

public final class WechatMsgProtos {
  private WechatMsgProtos() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WechatMsgOrBuilder extends
          // @@protoc_insertion_point(interface_extends:net.hzbox.vj.manager.proto.WechatMsg)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 company_id = 1;</code>
     */
    int getCompanyId();

    /**
     * <code>int32 app_id = 2;</code>
     */
    int getAppId();

    /**
     * <code>int32 business_type = 3;</code>
     */
    int getBusinessType();

    /**
     * <code>int32 business_id = 4;</code>
     */
    int getBusinessId();

    /**
     * <code>string send_time = 5;</code>
     */
    String getSendTime();
    /**
     * <code>string send_time = 5;</code>
     */
    com.google.protobuf.ByteString
    getSendTimeBytes();

    /**
     * <code>string person_ids = 6;</code>
     */
    String getPersonIds();
    /**
     * <code>string person_ids = 6;</code>
     */
    com.google.protobuf.ByteString
    getPersonIdsBytes();

    /**
     * <code>string depart_ids = 7;</code>
     */
    String getDepartIds();
    /**
     * <code>string depart_ids = 7;</code>
     */
    com.google.protobuf.ByteString
    getDepartIdsBytes();

    /**
     * <code>string tag_ids = 8;</code>
     */
    String getTagIds();
    /**
     * <code>string tag_ids = 8;</code>
     */
    com.google.protobuf.ByteString
    getTagIdsBytes();

    /**
     * <code>string exclude_person = 9;</code>
     */
    String getExcludePerson();
    /**
     * <code>string exclude_person = 9;</code>
     */
    com.google.protobuf.ByteString
    getExcludePersonBytes();

    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    java.util.List<WechatMsgNews>
    getMsgNewsList();
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getMsgNews(int index);
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    int getMsgNewsCount();
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    java.util.List<? extends WechatMsgNewsOrBuilder>
    getMsgNewsOrBuilderList();
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNewsOrBuilder getMsgNewsOrBuilder(
            int index);

    /**
     * <code>bool flag = 11;</code>
     */
    boolean getFlag();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.manager.proto.WechatMsg}
   */
  public  static final class WechatMsg extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:net.hzbox.vj.manager.proto.WechatMsg)
          WechatMsgOrBuilder {
    // Use WechatMsg.newBuilder() to construct.
    private WechatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WechatMsg() {
      companyId_ = 0;
      appId_ = 0;
      businessType_ = 0;
      businessId_ = 0;
      sendTime_ = "";
      personIds_ = "";
      departIds_ = "";
      tagIds_ = "";
      excludePerson_ = "";
      msgNews_ = java.util.Collections.emptyList();
      flag_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WechatMsg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              companyId_ = input.readInt32();
              break;
            }
            case 16: {

              appId_ = input.readInt32();
              break;
            }
            case 24: {

              businessType_ = input.readInt32();
              break;
            }
            case 32: {

              businessId_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              sendTime_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              personIds_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              departIds_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              tagIds_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              excludePerson_ = s;
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                msgNews_ = new java.util.ArrayList<WechatMsgNews>();
                mutable_bitField0_ |= 0x00000200;
              }
              msgNews_.add(
                      input.readMessage(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.parser(), extensionRegistry));
              break;
            }
            case 88: {

              flag_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          msgNews_ = java.util.Collections.unmodifiableList(msgNews_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.class, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.Builder.class);
    }

    private int bitField0_;
    public static final int COMPANY_ID_FIELD_NUMBER = 1;
    private int companyId_;
    /**
     * <code>int32 company_id = 1;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>int32 app_id = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int BUSINESS_TYPE_FIELD_NUMBER = 3;
    private int businessType_;
    /**
     * <code>int32 business_type = 3;</code>
     */
    public int getBusinessType() {
      return businessType_;
    }

    public static final int BUSINESS_ID_FIELD_NUMBER = 4;
    private int businessId_;
    /**
     * <code>int32 business_id = 4;</code>
     */
    public int getBusinessId() {
      return businessId_;
    }

    public static final int SEND_TIME_FIELD_NUMBER = 5;
    private volatile Object sendTime_;
    /**
     * <code>string send_time = 5;</code>
     */
    public String getSendTime() {
      Object ref = sendTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sendTime_ = s;
        return s;
      }
    }
    /**
     * <code>string send_time = 5;</code>
     */
    public com.google.protobuf.ByteString
    getSendTimeBytes() {
      Object ref = sendTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        sendTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_IDS_FIELD_NUMBER = 6;
    private volatile Object personIds_;
    /**
     * <code>string person_ids = 6;</code>
     */
    public String getPersonIds() {
      Object ref = personIds_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        personIds_ = s;
        return s;
      }
    }
    /**
     * <code>string person_ids = 6;</code>
     */
    public com.google.protobuf.ByteString
    getPersonIdsBytes() {
      Object ref = personIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        personIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEPART_IDS_FIELD_NUMBER = 7;
    private volatile Object departIds_;
    /**
     * <code>string depart_ids = 7;</code>
     */
    public String getDepartIds() {
      Object ref = departIds_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departIds_ = s;
        return s;
      }
    }
    /**
     * <code>string depart_ids = 7;</code>
     */
    public com.google.protobuf.ByteString
    getDepartIdsBytes() {
      Object ref = departIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        departIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_IDS_FIELD_NUMBER = 8;
    private volatile Object tagIds_;
    /**
     * <code>string tag_ids = 8;</code>
     */
    public String getTagIds() {
      Object ref = tagIds_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tagIds_ = s;
        return s;
      }
    }
    /**
     * <code>string tag_ids = 8;</code>
     */
    public com.google.protobuf.ByteString
    getTagIdsBytes() {
      Object ref = tagIds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        tagIds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCLUDE_PERSON_FIELD_NUMBER = 9;
    private volatile Object excludePerson_;
    /**
     * <code>string exclude_person = 9;</code>
     */
    public String getExcludePerson() {
      Object ref = excludePerson_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        excludePerson_ = s;
        return s;
      }
    }
    /**
     * <code>string exclude_person = 9;</code>
     */
    public com.google.protobuf.ByteString
    getExcludePersonBytes() {
      Object ref = excludePerson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        excludePerson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_NEWS_FIELD_NUMBER = 10;
    private java.util.List<WechatMsgNews> msgNews_;
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    public java.util.List<WechatMsgNews> getMsgNewsList() {
      return msgNews_;
    }
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    public java.util.List<? extends WechatMsgNewsOrBuilder>
    getMsgNewsOrBuilderList() {
      return msgNews_;
    }
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    public int getMsgNewsCount() {
      return msgNews_.size();
    }
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getMsgNews(int index) {
      return msgNews_.get(index);
    }
    /**
     * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
     */
    public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNewsOrBuilder getMsgNewsOrBuilder(
            int index) {
      return msgNews_.get(index);
    }

    public static final int FLAG_FIELD_NUMBER = 11;
    private boolean flag_;
    /**
     * <code>bool flag = 11;</code>
     */
    public boolean getFlag() {
      return flag_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (companyId_ != 0) {
        output.writeInt32(1, companyId_);
      }
      if (appId_ != 0) {
        output.writeInt32(2, appId_);
      }
      if (businessType_ != 0) {
        output.writeInt32(3, businessType_);
      }
      if (businessId_ != 0) {
        output.writeInt32(4, businessId_);
      }
      if (!getSendTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sendTime_);
      }
      if (!getPersonIdsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, personIds_);
      }
      if (!getDepartIdsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, departIds_);
      }
      if (!getTagIdsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tagIds_);
      }
      if (!getExcludePersonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, excludePerson_);
      }
      for (int i = 0; i < msgNews_.size(); i++) {
        output.writeMessage(10, msgNews_.get(i));
      }
      if (flag_ != false) {
        output.writeBool(11, flag_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, companyId_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, appId_);
      }
      if (businessType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, businessType_);
      }
      if (businessId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, businessId_);
      }
      if (!getSendTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sendTime_);
      }
      if (!getPersonIdsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, personIds_);
      }
      if (!getDepartIdsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, departIds_);
      }
      if (!getTagIdsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tagIds_);
      }
      if (!getExcludePersonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, excludePerson_);
      }
      for (int i = 0; i < msgNews_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(10, msgNews_.get(i));
      }
      if (flag_ != false) {
        size += com.google.protobuf.CodedOutputStream
                .computeBoolSize(11, flag_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg)) {
        return super.equals(obj);
      }
      net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg other = (net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg) obj;

      boolean result = true;
      result = result && (getCompanyId()
              == other.getCompanyId());
      result = result && (getAppId()
              == other.getAppId());
      result = result && (getBusinessType()
              == other.getBusinessType());
      result = result && (getBusinessId()
              == other.getBusinessId());
      result = result && getSendTime()
              .equals(other.getSendTime());
      result = result && getPersonIds()
              .equals(other.getPersonIds());
      result = result && getDepartIds()
              .equals(other.getDepartIds());
      result = result && getTagIds()
              .equals(other.getTagIds());
      result = result && getExcludePerson()
              .equals(other.getExcludePerson());
      result = result && getMsgNewsList()
              .equals(other.getMsgNewsList());
      result = result && (getFlag()
              == other.getFlag());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + BUSINESS_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessType();
      hash = (37 * hash) + BUSINESS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessId();
      hash = (37 * hash) + SEND_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendTime().hashCode();
      hash = (37 * hash) + PERSON_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getPersonIds().hashCode();
      hash = (37 * hash) + DEPART_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getDepartIds().hashCode();
      hash = (37 * hash) + TAG_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getTagIds().hashCode();
      hash = (37 * hash) + EXCLUDE_PERSON_FIELD_NUMBER;
      hash = (53 * hash) + getExcludePerson().hashCode();
      if (getMsgNewsCount() > 0) {
        hash = (37 * hash) + MSG_NEWS_FIELD_NUMBER;
        hash = (53 * hash) + getMsgNewsList().hashCode();
      }
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getFlag());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.manager.proto.WechatMsg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:net.hzbox.vj.manager.proto.WechatMsg)
            net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.class, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.Builder.class);
      }

      // Construct using net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMsgNewsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        companyId_ = 0;

        appId_ = 0;

        businessType_ = 0;

        businessId_ = 0;

        sendTime_ = "";

        personIds_ = "";

        departIds_ = "";

        tagIds_ = "";

        excludePerson_ = "";

        if (msgNewsBuilder_ == null) {
          msgNews_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          msgNewsBuilder_.clear();
        }
        flag_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor;
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg getDefaultInstanceForType() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.getDefaultInstance();
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg build() {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg buildPartial() {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg result = new net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.companyId_ = companyId_;
        result.appId_ = appId_;
        result.businessType_ = businessType_;
        result.businessId_ = businessId_;
        result.sendTime_ = sendTime_;
        result.personIds_ = personIds_;
        result.departIds_ = departIds_;
        result.tagIds_ = tagIds_;
        result.excludePerson_ = excludePerson_;
        if (msgNewsBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            msgNews_ = java.util.Collections.unmodifiableList(msgNews_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.msgNews_ = msgNews_;
        } else {
          result.msgNews_ = msgNewsBuilder_.build();
        }
        result.flag_ = flag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg) {
          return mergeFrom((net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg other) {
        if (other == net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg.getDefaultInstance()) return this;
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getBusinessType() != 0) {
          setBusinessType(other.getBusinessType());
        }
        if (other.getBusinessId() != 0) {
          setBusinessId(other.getBusinessId());
        }
        if (!other.getSendTime().isEmpty()) {
          sendTime_ = other.sendTime_;
          onChanged();
        }
        if (!other.getPersonIds().isEmpty()) {
          personIds_ = other.personIds_;
          onChanged();
        }
        if (!other.getDepartIds().isEmpty()) {
          departIds_ = other.departIds_;
          onChanged();
        }
        if (!other.getTagIds().isEmpty()) {
          tagIds_ = other.tagIds_;
          onChanged();
        }
        if (!other.getExcludePerson().isEmpty()) {
          excludePerson_ = other.excludePerson_;
          onChanged();
        }
        if (msgNewsBuilder_ == null) {
          if (!other.msgNews_.isEmpty()) {
            if (msgNews_.isEmpty()) {
              msgNews_ = other.msgNews_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureMsgNewsIsMutable();
              msgNews_.addAll(other.msgNews_);
            }
            onChanged();
          }
        } else {
          if (!other.msgNews_.isEmpty()) {
            if (msgNewsBuilder_.isEmpty()) {
              msgNewsBuilder_.dispose();
              msgNewsBuilder_ = null;
              msgNews_ = other.msgNews_;
              bitField0_ = (bitField0_ & ~0x00000200);
              msgNewsBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getMsgNewsFieldBuilder() : null;
            } else {
              msgNewsBuilder_.addAllMessages(other.msgNews_);
            }
          }
        }
        if (other.getFlag() != false) {
          setFlag(other.getFlag());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int companyId_ ;
      /**
       * <code>int32 company_id = 1;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>int32 company_id = 1;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 company_id = 1;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <code>int32 app_id = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>int32 app_id = 2;</code>
       */
      public Builder setAppId(int value) {

        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 app_id = 2;</code>
       */
      public Builder clearAppId() {

        appId_ = 0;
        onChanged();
        return this;
      }

      private int businessType_ ;
      /**
       * <code>int32 business_type = 3;</code>
       */
      public int getBusinessType() {
        return businessType_;
      }
      /**
       * <code>int32 business_type = 3;</code>
       */
      public Builder setBusinessType(int value) {

        businessType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 business_type = 3;</code>
       */
      public Builder clearBusinessType() {

        businessType_ = 0;
        onChanged();
        return this;
      }

      private int businessId_ ;
      /**
       * <code>int32 business_id = 4;</code>
       */
      public int getBusinessId() {
        return businessId_;
      }
      /**
       * <code>int32 business_id = 4;</code>
       */
      public Builder setBusinessId(int value) {

        businessId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 business_id = 4;</code>
       */
      public Builder clearBusinessId() {

        businessId_ = 0;
        onChanged();
        return this;
      }

      private Object sendTime_ = "";
      /**
       * <code>string send_time = 5;</code>
       */
      public String getSendTime() {
        Object ref = sendTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sendTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string send_time = 5;</code>
       */
      public com.google.protobuf.ByteString
      getSendTimeBytes() {
        Object ref = sendTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          sendTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string send_time = 5;</code>
       */
      public Builder setSendTime(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string send_time = 5;</code>
       */
      public Builder clearSendTime() {

        sendTime_ = getDefaultInstance().getSendTime();
        onChanged();
        return this;
      }
      /**
       * <code>string send_time = 5;</code>
       */
      public Builder setSendTimeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        sendTime_ = value;
        onChanged();
        return this;
      }

      private Object personIds_ = "";
      /**
       * <code>string person_ids = 6;</code>
       */
      public String getPersonIds() {
        Object ref = personIds_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          personIds_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string person_ids = 6;</code>
       */
      public com.google.protobuf.ByteString
      getPersonIdsBytes() {
        Object ref = personIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          personIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string person_ids = 6;</code>
       */
      public Builder setPersonIds(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        personIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string person_ids = 6;</code>
       */
      public Builder clearPersonIds() {

        personIds_ = getDefaultInstance().getPersonIds();
        onChanged();
        return this;
      }
      /**
       * <code>string person_ids = 6;</code>
       */
      public Builder setPersonIdsBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        personIds_ = value;
        onChanged();
        return this;
      }

      private Object departIds_ = "";
      /**
       * <code>string depart_ids = 7;</code>
       */
      public String getDepartIds() {
        Object ref = departIds_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          departIds_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string depart_ids = 7;</code>
       */
      public com.google.protobuf.ByteString
      getDepartIdsBytes() {
        Object ref = departIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          departIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string depart_ids = 7;</code>
       */
      public Builder setDepartIds(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        departIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string depart_ids = 7;</code>
       */
      public Builder clearDepartIds() {

        departIds_ = getDefaultInstance().getDepartIds();
        onChanged();
        return this;
      }
      /**
       * <code>string depart_ids = 7;</code>
       */
      public Builder setDepartIdsBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        departIds_ = value;
        onChanged();
        return this;
      }

      private Object tagIds_ = "";
      /**
       * <code>string tag_ids = 8;</code>
       */
      public String getTagIds() {
        Object ref = tagIds_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tagIds_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tag_ids = 8;</code>
       */
      public com.google.protobuf.ByteString
      getTagIdsBytes() {
        Object ref = tagIds_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          tagIds_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag_ids = 8;</code>
       */
      public Builder setTagIds(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        tagIds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag_ids = 8;</code>
       */
      public Builder clearTagIds() {

        tagIds_ = getDefaultInstance().getTagIds();
        onChanged();
        return this;
      }
      /**
       * <code>string tag_ids = 8;</code>
       */
      public Builder setTagIdsBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        tagIds_ = value;
        onChanged();
        return this;
      }

      private Object excludePerson_ = "";
      /**
       * <code>string exclude_person = 9;</code>
       */
      public String getExcludePerson() {
        Object ref = excludePerson_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          excludePerson_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string exclude_person = 9;</code>
       */
      public com.google.protobuf.ByteString
      getExcludePersonBytes() {
        Object ref = excludePerson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          excludePerson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exclude_person = 9;</code>
       */
      public Builder setExcludePerson(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        excludePerson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exclude_person = 9;</code>
       */
      public Builder clearExcludePerson() {

        excludePerson_ = getDefaultInstance().getExcludePerson();
        onChanged();
        return this;
      }
      /**
       * <code>string exclude_person = 9;</code>
       */
      public Builder setExcludePersonBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        excludePerson_ = value;
        onChanged();
        return this;
      }

      private java.util.List<WechatMsgNews> msgNews_ =
              java.util.Collections.emptyList();
      private void ensureMsgNewsIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          msgNews_ = new java.util.ArrayList<WechatMsgNews>(msgNews_);
          bitField0_ |= 0x00000200;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              WechatMsgNews, WechatMsgNews.Builder, WechatMsgNewsOrBuilder> msgNewsBuilder_;

      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public java.util.List<WechatMsgNews> getMsgNewsList() {
        if (msgNewsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgNews_);
        } else {
          return msgNewsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public int getMsgNewsCount() {
        if (msgNewsBuilder_ == null) {
          return msgNews_.size();
        } else {
          return msgNewsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getMsgNews(int index) {
        if (msgNewsBuilder_ == null) {
          return msgNews_.get(index);
        } else {
          return msgNewsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder setMsgNews(
              int index, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews value) {
        if (msgNewsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgNewsIsMutable();
          msgNews_.set(index, value);
          onChanged();
        } else {
          msgNewsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder setMsgNews(
              int index, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder builderForValue) {
        if (msgNewsBuilder_ == null) {
          ensureMsgNewsIsMutable();
          msgNews_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgNewsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder addMsgNews(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews value) {
        if (msgNewsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgNewsIsMutable();
          msgNews_.add(value);
          onChanged();
        } else {
          msgNewsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder addMsgNews(
              int index, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews value) {
        if (msgNewsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgNewsIsMutable();
          msgNews_.add(index, value);
          onChanged();
        } else {
          msgNewsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder addMsgNews(
              net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder builderForValue) {
        if (msgNewsBuilder_ == null) {
          ensureMsgNewsIsMutable();
          msgNews_.add(builderForValue.build());
          onChanged();
        } else {
          msgNewsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder addMsgNews(
              int index, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder builderForValue) {
        if (msgNewsBuilder_ == null) {
          ensureMsgNewsIsMutable();
          msgNews_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgNewsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder addAllMsgNews(
              Iterable<? extends WechatMsgNews> values) {
        if (msgNewsBuilder_ == null) {
          ensureMsgNewsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, msgNews_);
          onChanged();
        } else {
          msgNewsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder clearMsgNews() {
        if (msgNewsBuilder_ == null) {
          msgNews_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          msgNewsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public Builder removeMsgNews(int index) {
        if (msgNewsBuilder_ == null) {
          ensureMsgNewsIsMutable();
          msgNews_.remove(index);
          onChanged();
        } else {
          msgNewsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder getMsgNewsBuilder(
              int index) {
        return getMsgNewsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNewsOrBuilder getMsgNewsOrBuilder(
              int index) {
        if (msgNewsBuilder_ == null) {
          return msgNews_.get(index);  } else {
          return msgNewsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public java.util.List<? extends WechatMsgNewsOrBuilder>
      getMsgNewsOrBuilderList() {
        if (msgNewsBuilder_ != null) {
          return msgNewsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgNews_);
        }
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder addMsgNewsBuilder() {
        return getMsgNewsFieldBuilder().addBuilder(
                net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder addMsgNewsBuilder(
              int index) {
        return getMsgNewsFieldBuilder().addBuilder(
                index, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.getDefaultInstance());
      }
      /**
       * <code>repeated .net.hzbox.vj.manager.proto.WechatMsgNews msg_news = 10;</code>
       */
      public java.util.List<WechatMsgNews.Builder>
      getMsgNewsBuilderList() {
        return getMsgNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              WechatMsgNews, WechatMsgNews.Builder, WechatMsgNewsOrBuilder>
      getMsgNewsFieldBuilder() {
        if (msgNewsBuilder_ == null) {
          msgNewsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  WechatMsgNews, WechatMsgNews.Builder, WechatMsgNewsOrBuilder>(
                  msgNews_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          msgNews_ = null;
        }
        return msgNewsBuilder_;
      }

      private boolean flag_ ;
      /**
       * <code>bool flag = 11;</code>
       */
      public boolean getFlag() {
        return flag_;
      }
      /**
       * <code>bool flag = 11;</code>
       */
      public Builder setFlag(boolean value) {

        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool flag = 11;</code>
       */
      public Builder clearFlag() {

        flag_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.manager.proto.WechatMsg)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.manager.proto.WechatMsg)
    private static final net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg();
    }

    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WechatMsg>
            PARSER = new com.google.protobuf.AbstractParser<WechatMsg>() {
      public WechatMsg parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new WechatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WechatMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WechatMsg> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WechatMsgNewsOrBuilder extends
          // @@protoc_insertion_point(interface_extends:net.hzbox.vj.manager.proto.WechatMsgNews)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string title = 2;</code>
     */
    String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
    getTitleBytes();

    /**
     * <code>string discript = 3;</code>
     */
    String getDiscript();
    /**
     * <code>string discript = 3;</code>
     */
    com.google.protobuf.ByteString
    getDiscriptBytes();

    /**
     * <code>string url = 4;</code>
     */
    String getUrl();
    /**
     * <code>string url = 4;</code>
     */
    com.google.protobuf.ByteString
    getUrlBytes();

    /**
     * <code>string pic_url = 5;</code>
     */
    String getPicUrl();
    /**
     * <code>string pic_url = 5;</code>
     */
    com.google.protobuf.ByteString
    getPicUrlBytes();

    /**
     * <code>string create_time = 6;</code>
     */
    String getCreateTime();
    /**
     * <code>string create_time = 6;</code>
     */
    com.google.protobuf.ByteString
    getCreateTimeBytes();

    /**
     * <code>int32 company_id = 7;</code>
     */
    int getCompanyId();

    /**
     * <code>int32 delete_flag = 8;</code>
     */
    int getDeleteFlag();

    /**
     * <code>int32 msg_id = 9;</code>
     */
    int getMsgId();

    /**
     * <code>int32 paixu = 10;</code>
     */
    int getPaixu();
  }
  /**
   * Protobuf type {@code net.hzbox.vj.manager.proto.WechatMsgNews}
   */
  public  static final class WechatMsgNews extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:net.hzbox.vj.manager.proto.WechatMsgNews)
          WechatMsgNewsOrBuilder {
    // Use WechatMsgNews.newBuilder() to construct.
    private WechatMsgNews(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WechatMsgNews() {
      id_ = 0;
      title_ = "";
      discript_ = "";
      url_ = "";
      picUrl_ = "";
      createTime_ = "";
      companyId_ = 0;
      deleteFlag_ = 0;
      msgId_ = 0;
      paixu_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WechatMsgNews(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              discript_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              picUrl_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            case 56: {

              companyId_ = input.readInt32();
              break;
            }
            case 64: {

              deleteFlag_ = input.readInt32();
              break;
            }
            case 72: {

              msgId_ = input.readInt32();
              break;
            }
            case 80: {

              paixu_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.class, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCRIPT_FIELD_NUMBER = 3;
    private volatile Object discript_;
    /**
     * <code>string discript = 3;</code>
     */
    public String getDiscript() {
      Object ref = discript_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        discript_ = s;
        return s;
      }
    }
    /**
     * <code>string discript = 3;</code>
     */
    public com.google.protobuf.ByteString
    getDiscriptBytes() {
      Object ref = discript_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        discript_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 4;
    private volatile Object url_;
    /**
     * <code>string url = 4;</code>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 4;</code>
     */
    public com.google.protobuf.ByteString
    getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PIC_URL_FIELD_NUMBER = 5;
    private volatile Object picUrl_;
    /**
     * <code>string pic_url = 5;</code>
     */
    public String getPicUrl() {
      Object ref = picUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        picUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string pic_url = 5;</code>
     */
    public com.google.protobuf.ByteString
    getPicUrlBytes() {
      Object ref = picUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        picUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 6;
    private volatile Object createTime_;
    /**
     * <code>string create_time = 6;</code>
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <code>string create_time = 6;</code>
     */
    public com.google.protobuf.ByteString
    getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 7;
    private int companyId_;
    /**
     * <code>int32 company_id = 7;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    public static final int DELETE_FLAG_FIELD_NUMBER = 8;
    private int deleteFlag_;
    /**
     * <code>int32 delete_flag = 8;</code>
     */
    public int getDeleteFlag() {
      return deleteFlag_;
    }

    public static final int MSG_ID_FIELD_NUMBER = 9;
    private int msgId_;
    /**
     * <code>int32 msg_id = 9;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    public static final int PAIXU_FIELD_NUMBER = 10;
    private int paixu_;
    /**
     * <code>int32 paixu = 10;</code>
     */
    public int getPaixu() {
      return paixu_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getDiscriptBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, discript_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
      }
      if (!getPicUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, picUrl_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createTime_);
      }
      if (companyId_ != 0) {
        output.writeInt32(7, companyId_);
      }
      if (deleteFlag_ != 0) {
        output.writeInt32(8, deleteFlag_);
      }
      if (msgId_ != 0) {
        output.writeInt32(9, msgId_);
      }
      if (paixu_ != 0) {
        output.writeInt32(10, paixu_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getDiscriptBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, discript_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
      }
      if (!getPicUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, picUrl_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createTime_);
      }
      if (companyId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(7, companyId_);
      }
      if (deleteFlag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(8, deleteFlag_);
      }
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(9, msgId_);
      }
      if (paixu_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(10, paixu_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews)) {
        return super.equals(obj);
      }
      net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews other = (net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews) obj;

      boolean result = true;
      result = result && (getId()
              == other.getId());
      result = result && getTitle()
              .equals(other.getTitle());
      result = result && getDiscript()
              .equals(other.getDiscript());
      result = result && getUrl()
              .equals(other.getUrl());
      result = result && getPicUrl()
              .equals(other.getPicUrl());
      result = result && getCreateTime()
              .equals(other.getCreateTime());
      result = result && (getCompanyId()
              == other.getCompanyId());
      result = result && (getDeleteFlag()
              == other.getDeleteFlag());
      result = result && (getMsgId()
              == other.getMsgId());
      result = result && (getPaixu()
              == other.getPaixu());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DISCRIPT_FIELD_NUMBER;
      hash = (53 * hash) + getDiscript().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + PIC_URL_FIELD_NUMBER;
      hash = (53 * hash) + getPicUrl().hashCode();
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId();
      hash = (37 * hash) + DELETE_FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteFlag();
      hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + PAIXU_FIELD_NUMBER;
      hash = (53 * hash) + getPaixu();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.hzbox.vj.manager.proto.WechatMsgNews}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:net.hzbox.vj.manager.proto.WechatMsgNews)
            net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.class, net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.Builder.class);
      }

      // Construct using net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        discript_ = "";

        url_ = "";

        picUrl_ = "";

        createTime_ = "";

        companyId_ = 0;

        deleteFlag_ = 0;

        msgId_ = 0;

        paixu_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor;
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getDefaultInstanceForType() {
        return net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.getDefaultInstance();
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews build() {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews buildPartial() {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews result = new net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews(this);
        result.id_ = id_;
        result.title_ = title_;
        result.discript_ = discript_;
        result.url_ = url_;
        result.picUrl_ = picUrl_;
        result.createTime_ = createTime_;
        result.companyId_ = companyId_;
        result.deleteFlag_ = deleteFlag_;
        result.msgId_ = msgId_;
        result.paixu_ = paixu_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews) {
          return mergeFrom((net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews other) {
        if (other == net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDiscript().isEmpty()) {
          discript_ = other.discript_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getPicUrl().isEmpty()) {
          picUrl_ = other.picUrl_;
          onChanged();
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        if (other.getCompanyId() != 0) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getDeleteFlag() != 0) {
          setDeleteFlag(other.getDeleteFlag());
        }
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (other.getPaixu() != 0) {
          setPaixu(other.getPaixu());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
      getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {

        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        title_ = value;
        onChanged();
        return this;
      }

      private Object discript_ = "";
      /**
       * <code>string discript = 3;</code>
       */
      public String getDiscript() {
        Object ref = discript_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          discript_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string discript = 3;</code>
       */
      public com.google.protobuf.ByteString
      getDiscriptBytes() {
        Object ref = discript_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          discript_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string discript = 3;</code>
       */
      public Builder setDiscript(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        discript_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string discript = 3;</code>
       */
      public Builder clearDiscript() {

        discript_ = getDefaultInstance().getDiscript();
        onChanged();
        return this;
      }
      /**
       * <code>string discript = 3;</code>
       */
      public Builder setDiscriptBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        discript_ = value;
        onChanged();
        return this;
      }

      private Object url_ = "";
      /**
       * <code>string url = 4;</code>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string url = 4;</code>
       */
      public com.google.protobuf.ByteString
      getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 4;</code>
       */
      public Builder setUrl(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 4;</code>
       */
      public Builder clearUrl() {

        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 4;</code>
       */
      public Builder setUrlBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        url_ = value;
        onChanged();
        return this;
      }

      private Object picUrl_ = "";
      /**
       * <code>string pic_url = 5;</code>
       */
      public String getPicUrl() {
        Object ref = picUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          picUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pic_url = 5;</code>
       */
      public com.google.protobuf.ByteString
      getPicUrlBytes() {
        Object ref = picUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          picUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pic_url = 5;</code>
       */
      public Builder setPicUrl(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        picUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pic_url = 5;</code>
       */
      public Builder clearPicUrl() {

        picUrl_ = getDefaultInstance().getPicUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string pic_url = 5;</code>
       */
      public Builder setPicUrlBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        picUrl_ = value;
        onChanged();
        return this;
      }

      private Object createTime_ = "";
      /**
       * <code>string create_time = 6;</code>
       */
      public String getCreateTime() {
        Object ref = createTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string create_time = 6;</code>
       */
      public com.google.protobuf.ByteString
      getCreateTimeBytes() {
        Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string create_time = 6;</code>
       */
      public Builder setCreateTime(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string create_time = 6;</code>
       */
      public Builder clearCreateTime() {

        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string create_time = 6;</code>
       */
      public Builder setCreateTimeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        createTime_ = value;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>int32 company_id = 7;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>int32 company_id = 7;</code>
       */
      public Builder setCompanyId(int value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 company_id = 7;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0;
        onChanged();
        return this;
      }

      private int deleteFlag_ ;
      /**
       * <code>int32 delete_flag = 8;</code>
       */
      public int getDeleteFlag() {
        return deleteFlag_;
      }
      /**
       * <code>int32 delete_flag = 8;</code>
       */
      public Builder setDeleteFlag(int value) {

        deleteFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 delete_flag = 8;</code>
       */
      public Builder clearDeleteFlag() {

        deleteFlag_ = 0;
        onChanged();
        return this;
      }

      private int msgId_ ;
      /**
       * <code>int32 msg_id = 9;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>int32 msg_id = 9;</code>
       */
      public Builder setMsgId(int value) {

        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msg_id = 9;</code>
       */
      public Builder clearMsgId() {

        msgId_ = 0;
        onChanged();
        return this;
      }

      private int paixu_ ;
      /**
       * <code>int32 paixu = 10;</code>
       */
      public int getPaixu() {
        return paixu_;
      }
      /**
       * <code>int32 paixu = 10;</code>
       */
      public Builder setPaixu(int value) {

        paixu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 paixu = 10;</code>
       */
      public Builder clearPaixu() {

        paixu_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:net.hzbox.vj.manager.proto.WechatMsgNews)
    }

    // @@protoc_insertion_point(class_scope:net.hzbox.vj.manager.proto.WechatMsgNews)
    private static final net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews();
    }

    public static net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WechatMsgNews>
            PARSER = new com.google.protobuf.AbstractParser<WechatMsgNews>() {
      public WechatMsgNews parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new WechatMsgNews(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WechatMsgNews> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WechatMsgNews> getParserForType() {
      return PARSER;
    }

    public net.hzbox.vj.manager.proto.WechatMsgProtos.WechatMsgNews getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_net_hzbox_vj_manager_proto_WechatMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\020wechat_msg.proto\022\032net.hzbox.vj.manager" +
                    ".proto\"\212\002\n\tWechatMsg\022\022\n\ncompany_id\030\001 \001(\005" +
                    "\022\016\n\006app_id\030\002 \001(\005\022\025\n\rbusiness_type\030\003 \001(\005\022" +
                    "\023\n\013business_id\030\004 \001(\005\022\021\n\tsend_time\030\005 \001(\t\022" +
                    "\022\n\nperson_ids\030\006 \001(\t\022\022\n\ndepart_ids\030\007 \001(\t\022" +
                    "\017\n\007tag_ids\030\010 \001(\t\022\026\n\016exclude_person\030\t \001(\t" +
                    "\022;\n\010msg_news\030\n \003(\0132).net.hzbox.vj.manage" +
                    "r.proto.WechatMsgNews\022\014\n\004flag\030\013 \001(\010\"\267\001\n\r" +
                    "WechatMsgNews\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t" +
                    "\022\020\n\010discript\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\017\n\007pic_u",
            "rl\030\005 \001(\t\022\023\n\013create_time\030\006 \001(\t\022\022\n\ncompany" +
                    "_id\030\007 \001(\005\022\023\n\013delete_flag\030\010 \001(\005\022\016\n\006msg_id" +
                    "\030\t \001(\005\022\r\n\005paixu\030\n \001(\005B-\n\032net.hzbox.vj.ma" +
                    "nager.protoB\017WechatMsgProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_net_hzbox_vj_manager_proto_WechatMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_net_hzbox_vj_manager_proto_WechatMsg_descriptor,
            new String[] { "CompanyId", "AppId", "BusinessType", "BusinessId", "SendTime", "PersonIds", "DepartIds", "TagIds", "ExcludePerson", "MsgNews", "Flag", });
    internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_net_hzbox_vj_manager_proto_WechatMsgNews_descriptor,
            new String[] { "Id", "Title", "Discript", "Url", "PicUrl", "CreateTime", "CompanyId", "DeleteFlag", "MsgId", "Paixu", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
